<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array (
	// ======= BEGIN v4 LOCALES =======
	'actionvariables' => 'Variables',
	'livechat' => 'Live Chat',
	'rules' => 'Reglas',
	'insertgroup' => 'Insertar Grupo',
	'editgroup' => 'Editar Grupo',
	'insertban' => 'Insertar Bloqueo',
	'editban' => 'Edita Bloqueo',
	'actionvisitorexperience' => 'Experiencia Visitante',
	'actionstaffalerts' => 'Alertas Personal',
	'hexcode' => 'Código de Color Hex',
	'wineditgroup' => 'Editar Grupo Visitante: %s',
	'visitorgroups' => 'Grupos Visitantes',
	'titlenorulecriteria' => 'No se indicó un criterio',
	'msgnorulecriteria' => SWIFT_PRODUCT . ' no puede insertar una regla de visitante puesto que no se ha especificado un criterio.',
	'titlenoruleactions' => 'No se especificó ninguna acción',
	'msgnoruleactions' => SWIFT_PRODUCT . ' no ha podido insertar la regla de visitante puesto que no se han definido acciones.',
	'invalidgroup' => 'El grupo especificado no es válido. Por favor, asegúrate de que el grupo visitante existe y que la base de datos no esté corrompida',
	'visitorgrouptitle' => 'Título Grupo Visitante',
	'desc_visitorgrouptitle' => 'Por favor, indica un título para este Grupo Visitante.',
	'groupcolor' => 'Color de Grupo',
	'desc_groupcolor' => 'Especifica un color para el título de este grupo, que será mostrado en la parrilla de visitantes.',
	'lastupdate' => 'Última Actualización',
	'titledelvisitorgroup' => 'Borrados "%d" Grupos Visitantes',
	'msgdelvisitorgroup' => 'Se han eliminado correctamente los siguientes grupos de visitantes de la base de datos:',
	'titleinsertgroup' => 'Grupo Visitante Insertado "%s"',
	'msginsertgroup' => 'Se ha insertado correctamente el grupo visitante "<font color="%s">%s</font>" en la base de datos.',
	'titleupdategroup' => 'Grupo Visitante Actualizado "%s"',
	'msgupdategroup' => 'Se ha actualizado correctamente el grupo visitante "<font color="%s">%s</font>".',
	'isregex' => '¿Es una Expresión Regular?',
	'desc_isregex' => 'Si se activa,'.SWIFT_PRODUCT.' comparará las IPs de los visitantes usando la expresión regular indicada arriba.',
	'titleinsertban' => 'Bloqueo de Visitante Insertado',
	'msginsertban' => 'Se ha insertado el bloqueo al visitante "%s" en la base de datos.',
	'titleupdateban' => 'Bloqueo Visitante actualizado',
	'msgupdateban' => 'Se ha actualizado correctamente el bloqueo de visitante "%s"',
	'wineditban' => 'Editar Bloqueo: %s',
	'gridisregex' => '¿RegEx?',
	'titledelbans' => 'Eliminados "%d" Bloqueos de Visitantes',
	'msgdelbans' => 'Se han eliminado los siguientes bloqueos de visitantes de la base de datos:',
	'onlinestatus' => 'Estado Online',
	'desc_onlinestatus' => '',
	'disconnect' => 'Desconecta',
	'logintime' => 'Identificación',
	'lastactivity' => 'Última Actividad',
	'username' => 'Usuario',
	'fullname' => 'Nombre',
	'titledcstaff' => 'Desconectado "%d" Usuarios de Personal identificados',
	'msgdcstaff' => 'Se han desconectado los siguientes usuarios de personal:',
	'skills' => 'Especialidad',
	'desc_skills' => '',
	'skilltitle' => 'Título Especialidad',
	'alertemail' => 'Email de Alerta',
	'wineditskill' => 'Editar Especialidad: %s',
	'messagerouting' => 'Enrutado del Mensaje',
	'desc_messagerouting' => '',
	'mrdepartment' => 'Departamento',
	'mraction' => 'Accción',
	'titleupdmr' => 'Reglas de Enrutamiento del Mensaje actualizadas',
	'msgupdmr' => 'Se ha actualizado correctamente las reglas de enrutado de mensajes. Los detalles se muestran a continuación:',
	'routetotickets' => 'Ruta a los Tickets',
	'mrdepartment' => 'Departamento',
	'routetoemail' => 'Ruta al Email',
	'mremail' => 'Email(s)',
	'insertrule' => 'Insertar Regla',
	'desc_insertrule' => '',
	'insertcriteria' => 'Insertar Criterio',
	'tabactions' => 'Acciones',
	'insertaction' => 'Insertar Acción',
	'ruletitle' => 'Título Regla',
	'desc_ruletitle' => 'Introduce el Título de la Regla',
	'rulestop' => 'Reglas de Interrupción de Procesado',
	'desc_rulestop' => 'Si se activa, otras reglas no se procesarán si se cumplen los requisitos especificados a continuación.',
	'sortorder' => 'Orden',
	'desc_sortorder' => 'Especifica en qué orden se procesarán las Reglas; siempre en orden Ascendente..',
	'criteria' => 'Criterio',
	'smatchall' => 'Coincidir todos (AND)',
	'smatchany' => 'Coincidir cualquiera (OR)',
	'matchtype' => 'Opciones de Criterio',
	'smatchtype' => 'Tipo de Coincidencia',
	'desc_matchtype' => 'Selecciona el método de agrupamiento para los campos de criterio.',
	'clearall' => 'Limpiar todo',
	'titlevrcoreerror' => 'Error de Núcleo: falló la inserción',
	'msgvrcoreerror' => 'No se pudo insertar la Regla de Visitante',
	'invalidvisitorrule' => 'ERROR: Regla de Visitante inválida. Asegúrate de que la regla existe en la base de datos',
	'editrule' => 'Editar Regla',
	'desc_editrule' => '',
	'if' => 'Si',
	'titleinsertrule' => 'Regla de Visitante Insertada "%s"',
	'msginsertrule' => 'Se insertó correctamente la regla de visitante "%s" en la base de datos.',
	'actaddvariable' => '<b>Variable:</b> %s = %s',
	'actvisitorexperience' => '<b>Experiencia Usuario:</b> %s',
	'actstaffalert' => '<b>Alarta Personal:</b> Título: %s, Valor: %s',
	'actsetskill' => '<b>Definir Especialidad:</b> Título Especialidad: %s',
	'actsetgroup' => '<b>Definir Grupo:</b> Título Grupo Visitante: %s',
	'actsetdepartment' => '<b>Definir Departamento:</b> Título Departamento: %s',
	'actsetcolor' => '<b>Definir Color:</b> Código de Color: %s',
	'actbanvisitor' => '<b>Bloquear Visitante:</b> Tipo: %s',
	'titleupdaterule' => 'Regla de Visitante Actualizada "%s"',
	'msgupdaterule' => 'La regla de visitante se actualizó correctamente "%s".',
	'titledelvrules' => 'Eliminadas "%s" Reglas de Visitante',
	'msgdelvrules' => 'Se eliminaron las siguientes reglas de visitante.<br>%s',
	'settings' => 'Opciones',
	'lssettings' => 'Opciones',
	'desc_lssettings' => '',
	'tabsettings' => 'Opciones',
	'insertskill' => 'Insertar Especialidad',
	'desc_insertskill' => '',
	'tabassignments' => 'Asignaciones',
	'skilltitle' => 'Título Especialidad',
	'desc_skilltitle' => 'Introduce el Título de la Especialidad',
	'skilldesc' => 'Descripción de la Especialidad',
	'desc_skilldesc' => 'Introduce la descripción de la Especialidad. Máximo de 255 caracteres.',
	'skillemail' => 'Email',
	'desc_skillemail' => 'Introduce la dirección de correo del grupo de la Especialidad',
	'skillsperm' => 'Asignaciones del Personal',
	'ruletype' => 'Activador de Regla',
	'desc_ruletype' => 'Selecciona las acciones de llevar a cabo cuando la regla se active',
	'ruletype_1' => 'Cuando haya un chat',
	'ruletype_2' => 'Cuando un visitante entre en la página',
	'ruletype_3' => 'Cuando un visitante entre en la web',
	'ruletype_4' => 'Cuando un visitante esté en en espera',
	'actionsetskill' => 'Definid Especialidad',
	'actionsetdepartment' => 'Definir Departamento',
	'actionsetgroup' => 'Definir Grupo',
	'actionsetcolor' => 'Definir Color',
	'actionbanvisitor' => 'Bloquear Visitante',
	'notavailable' => '-- No Disponible --',
	'inlinechat' => 'Chat en línea',
	'engagevisitor' => 'Captación Visitantes',
	'customengagevisitor' => 'Captación Visitantes (Personalizado)',
	'editskill' => 'Editar Especialidad',
	'invalidchatskill' => 'Especialidad de Chat Inválida. Por favor, asegúrate de que la especialidad de chat existe en la base de datos.',
	'titledelchatskills' => 'Eliminadas "%d" Especialidades de Chat',
	'msgdelchatskills' => 'Se han eliminado las siguientes especialidades de chat de la base de datos:<br />%s',
	'titleinsertskill' => 'Especialidad de Chat Insertada',
	'msginsertskill' => 'Se han insertado "%s" Especialidades de Chat en la base de datos.',
	'titleupdateskill' => 'Especialidad de Chat Actualizada',
	'msgupdateskill' => 'Se han actualizado "%s" Especialidades de Chat.',
	'preservemessage' => 'Conservar Registro de mensajes',
	'seperatevia' => 'separar vía ;',

	// ======= RULE STRINGS =======
	'rule_currentpage' => 'Navegando - Página actual',
	'desc_rule_currentpage' => 'Página activa por el visitante está viendo en este momento',
	'rule_currentpageurl' => 'Visitante - Página Actual (URL)',
	'desc_rule_currentpageurl' => 'Página activa por el visitante está viendo en este momento',
	'rule_currentpagetitle' => 'Visitante - Página Actual (Título)',
	'desc_rule_currentpagetitle' => 'Página activa por el visitante está viendo en este momento',
	'rule_numberofpages' => 'Navegación - Número de Páginas',
	'desc_rule_numberofpages' => 'Número de páginas que el visitante ha abierto en la sesión activa',
	'rule_previouspagetitle' => 'Navegación - Página Anterior (Título)',
	'desc_rule_previouspagetitle' => 'Página activa que el visitante abrió previamente',
	'rule_previouspageurl' => 'Navegación - Página Anterior (URL)',
	'desc_rule_previouspageurl' => 'Página activa que el visitante abrió anteriormente',
	'rule_referringurl' => 'Navegación - URL de Redirección',
	'desc_rule_referringurl' => 'URL de origen a la página activa',
	'rule_searchenginefound' => 'Navegación - Localización por Motores de Búsqueda',
	'desc_rule_searchenginefound' => 'Propiedades Booleanas basadas en si el visitante fue referido por un motor de búsqueda',
	'rule_searchenginename' => 'Navegación - Nombre de Motor de Búsqueda',
	'desc_rule_searchenginename' => 'El motor de búsqueda desde el que visitante fue referido',
	'rule_searchenginequery' => 'Navegación - Cadena del Motor de Búsqueda',
	'desc_rule_searchenginequery' => 'La cadena que fue usada en la búsqueda',
	'rule_visitedpagetitle' => 'Navegación - Páginas Visitadas (Título)',
	'desc_rule_visitedpagetitle' => 'Todas las páginas que el visitante ha visitado en la sesión activa',
	'rule_visitedpageurl' => 'Navegación - Páginas Visitadas (URL)',
	'desc_rule_visitedpageurl' => 'Todas las páginas que el visitante ha visitado en la sesión activa',
	'rule_repeatvisit' => 'Visitante - Repetición de la Visita',
	'desc_rule_repeatvisit' => 'Si un visitante nuevo o repetidor',
	'rule_browser' => 'Visitante - Navegador',
	'desc_rule_browser' => 'Navegador de internet usado por el visitante: Safari, Mozilla, Internet Explorer',
	'rule_ipaddress' => 'Visitante - Dirección IP',
	'desc_rule_ipaddress' => 'La dirección IP del visitante',
	'rule_onlinestaff' => 'Personal - Personal Online',
	'desc_rule_onlinestaff' => 'Propiedad basada en el estado del os usuarios de personal online',
	'rule_onlinestaffskills' => 'Personal - Personal Online con Especialidad',
	'desc_rule_onlinestaffskills' => 'Propiedad basada en el estado del personal online con la especialidad especificada',
	'rule_onlinestaffdepartments' => 'Personal - Personal Online asignado a un departamento',
	'desc_rule_onlinestaffdepartments' => 'Propiedad basada en el estado del personal asignado a un departamento específico',
	'rule_timeinsite' => 'Tiempo - Tiempo en la web',
	'desc_rule_timeinsite' => 'Tiempo Total pasado en la web',
	'rule_timeinchat' => 'Tiempo - Tiempo en el Chat',
	'desc_rule_timeinchat' => 'Tiempo total empleado en un chat activo',
	'rule_timeagententry' => 'Tiempo - Segundos desde la última respuesta del personal',
	'desc_rule_timeagententry' => 'Número de segundos desde el último mensaje del personal',
	'rule_timevisitorentry' => 'Tiempo - Segundos desde el último mensaje de un visitante',
	'desc_rule_timevisitorentry' => 'Número de segundos desde el último mensaje de un visitante',
	'rule_timeagentvisitorentry' => 'Tiempo - Segundos desde el último mensaje del personal o del visitante',
	'desc_timeagentvisitorentry' => 'Número de segundos desde el último mensaje del personal o visitante',
	'rule_chatagentlastmessage' => 'Chat - Último mensaje del personal',
	'desc_rule_chatagentlastmessage' => 'El contenido del último mensaje del personal',
	'rule_chatvisitorlastmessage' => 'Chat - Último mensaje del visitante',
	'desc_rule_chatvisitorlastmessage' => 'El contenido del último mensaje del visitante',
	'rule_chatwithagentmessage' => 'Chat - Chat mensaje del personal',
	'desc_rule_chatwithagentmessage' => 'Booleano basado en si hay mensaje del personal en el chat',
	'rule_chatwithvisitormessage' => 'Chat - Chat con mensaje de visitante',
	'desc_rule_chatwithvisitormessage' => 'Booleano basado en si hay mensaje de visitante en el chat',
	'rule_chatwithagentvisitormessage' => 'Chat - Chat con personal o mensaje de visitante',
	'desc_rule_chatwithagentvisitormessage' => 'Booleano basado en si hay mensaje del personal o visitante en el char',
	'rule_chatinchat' => 'Chat - En Chat',
	'desc_rule_chatinchat' => 'Booleano basado en si el chat ha sido aceptado por un usuario del personal',
	'rule_chatrefusedchat' => 'Chat - Chat Rechazado',
	'desc_rule_chatrefusedchat' => 'Booleano basado en si el chat ha sido rechazado por el personal',
	'rule_geocountry' => 'GeoIP - País',
	'desc_rule_geocountry' => '',
	'rule_geocity' => 'GeoIP - Ciudad',
	'desc_rule_geocity' => '',
	'rule_geoipregion' => 'GeoIP - Región',
	'desc_rule_geoipregion' => '',
	'rule_geoorganization' => 'GeoIP - Organización',
	'desc_rule_geoorganization' => '',
	'rule_geotimezone' => 'GeoIP - Zona Horaria',
	'desc_rule_geotimezone' => '',
	'rule_geoisp' => 'GeoIP - ISP',
	'desc_rule_geoisp' => '',
	'rule_geoconnectiontype' => 'GeoIP - Velocidad de la Red',
	'desc_rule_geoconnectiontype' => '',
	'rule_geoippostalcode' => 'GeoIP - Código Postal',
	'desc_rule_geoippostalcode' => '',
	'rule_geoipmetrocode' => 'GeoIP - Código Metropolitano',
	'desc_rule_geoipmetrocode' => '',
	'rule_geoipareacode' => 'GeoIP - Código Área',
	'desc_rule_geoipareacode' => '',
	'rule_geoiplatitude' => 'GeoIP - Latitud',
	'desc_rule_geoiplatitude' => '',
	'rule_geoiplongitude' => 'GeoIP - Longitud',
	'desc_rule_geoiplongitude' => '',
	// ======= END v4 LOCALES =======


	'livesupport' => 'Live Chat',
	'visitorbans' => 'Bloqueos Visitantes',
	'desc_visitorbans' => 'Visitantes se bloquean por dirección IP. Los bloqueos de Visitante se pueden añadir desde la aplicación de escritorio LiveResponse. Los visitantes bloqueados no aparecerán en el seguimiento de visitantes y no podrán ver el estado del chat en el botón de la interfaz de cliente.',
	'visitorbanlist' => 'Lista de Bloqueos de Visitantes',
	'ipaddress' => 'Dirección IP',
	'desc_ipaddress' => 'Introduce la dirección IP a bloquear.',
	'addedby' => 'Creado por',
	'bandate' => 'Fecha Creación',
	'insertvisitorban' => 'Insertar Bloqueo Visitante',
	'invalidip' => 'ERROR: Dirección IP incorrecta',
	'ipinsertconfirm' => 'El Bloqueo de visitantes por dirección "%s" se ha insertado correctamente',
	'ipupdateconfirm' => 'El bloqueo de IP para la dirección "%s" ha sido actualizado',
	'ipdelconfirm' => 'Bloqueo de visitante eliminado correctamente',
	'invalidban' => 'Entrada de bloqueo de visitante incorrecta',
	'updatevisitorban' => 'Actualizar Bloqueo Visitante',
);
?>