<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array (
	// ======= BEGIN v4 LOCALES =======
	'tickets' => 'Tickets',
	'insertworkflow' => 'Flujo',
	'desc_insertworkflow' => '',
	'tabgeneral' => 'General',
	'tabactions' => 'Acciones',
	'workflowtitle' => 'Título Flujo',
	'desc_workflowtitle' => 'Introduce el Título para el Flujo de Trabajo',
	'isenabled' => '¿Activado?',
	'desc_isenabled' => 'Conmuta la ejecución de este Flujo de trabajo activando/desactivando esta opción.',
	'triggerevent' => 'Activación',
	'desc_triggerevent' => 'Selecciona el evento que activará este Flujo de trabajo',
	'insertcriteria' => 'Insertar Criterio',
	'sortorder' => 'Orden',
	'desc_sortorder' => 'Especifica el orden para este flujo de trabajo. Las reglas se procesarán en orden ascendente.',
	'smatchtype' => 'Tipo de Coincidencia',
	'matchtype' => 'Opciones de Criterio',
	'desc_matchtype' => 'Selecciona el siguiente método de agrupamiento para los cambios de criterio.',
	'smatchall' => 'Coincidir Todo (AND)',
	'smatchany' => 'Coincidir Cualquiera (OR)',
	'editworkflow' => 'Editar Flujo',
	'desc_editworkflow' => '',
	'invalidworkflowrule' => 'Flujo de trabajo inválido. Por favor, asegúrate de que el registro existe en la base de datos.',
	'manageworkflows' => 'Flujos',
	'desc_manageworkflows' => '',
	'creationdate' => 'Fecha Creación',
	'titleworkflowdel' => 'Eliminados "%d" Flujos de Trabajo',
	'msgworkflowdel' => 'Se han eliminado los siguientes Flujos de trabajo para Tickets:',
	'tabnotifications' => 'Notificaciones',
	'insertnotification' => 'Insertar Notificación',

	'tabpermissions' => 'Permisos',
	'staffvisibilitycustom' => '¿Restringir el Cambio a Equipos de Personal?',
	'desc_staffvisibilitycustom' => 'Si se activa, el flujo de trabajo será visible y podrá ser ejecutado únicamente por miembros de personal.',
	'staffgroups' => 'Equipos de Personal',

	// Actions
	'nochange' => '-- Sin Cambios --',
	'actionstaff' => 'Asignar a Personal',
	'desc_actionstaff' => '',
	'actionpriority' => 'Cambiar Prioridad',
	'desc_actionpriority' => '',
	'actionticketstatus' => 'Cambiar Estado Ticket',
	'desc_actionticketstatus' => '',
	'actiondepartment' => 'Mover a Departamento',
	'desc_actiondepartment' => '',
	'actionslaplan' => 'Cambiar Plan SLA',
	'desc_actionslaplan' => '',
	'actionflagtype' => 'Cambiar Tipo de Marca',
	'desc_actionflagtype' => '',
	'noplanavailable' => '-- No Disponible --',
	'actionnotes' => 'Añadir Notas',
	'desc_actionnotes' => '',
	'titlenoaction' => 'Sin Acción Seleccionada',
	'msgnoaction' => 'Necesitas seleccionar al menos una acción a ejecutar en caso de coincidencia con el criterio seleccionado para este flujo de trabajo.',
	'actionaddtags' => 'Añadir Etiquetas',
	'desc_actionaddtags' => '',
	'actionremovetags' => 'Eliminar Etiquetas',
	'desc_actionremovetags' => '',
	'actiontickettype' => 'Cambiar Tipo de Ticket',
	'desc_tickettype' => '',
	'actiontrainbayesian' => 'Entrenar Bayesiano',
	'desc_trainbayesian' => '',
	'actiontrash' => 'Mover a la Papelera',
	'desc_actiontrash' => '',

	// Trigger Events
	'tecron' => 'Tarea Programada (Ejecución automatizada recurrente)',
	'desc_tecron' => 'Este evento se activará cada vez que se ejecute una tarea programada. Lo normal es que sea cada 3-5 minutos dependiendo de la ejecución  de cron pseudo/manual.',
	'teticketcreation' => 'Creación de Ticket',
	'desc_teticketcreation' => 'Este evento se activará cuando se cree un nuevo ticket',
	'teslaplan' => 'Cambiar Plan SLA',
	'desc_teslaplan' => 'Este evento se activará cuando se cambia un Plan SLA',
	'teflag' => 'Cambio Marca',
	'desc_teflag' => 'Este evento se activará cuando se cambie el tipo de marca de un ticket',
	'temarkdue' => 'Ticket Marcado como Vencido',
	'desc_temarkdue' => 'Este evento se activará cuando un ticket esté marcado como vencido',
	'teaddrecipients' => 'Añadir Destinatarios',
	'desc_teaddrecipients' => 'Este evento se activará cuando se añada destinatarios a un ticket',
	'teupdateproperties' => 'Actualizar Propiedades',
	'desc_teupdateproperties' => 'Este evento se activará cuando se actualicen las propiedades del ticket',
	'testaffreply' => 'Respuesta Personal',
	'desc_testaffreply' => 'Este evento se activará cuando alguien del personal responda un ticket',
	'teuserreply' => 'Respuesta Usuario',
	'desc_teuserreply' => 'Este evento se activará cuando un usuario responda a un ticket',
	'teticketnote' => 'Nota de Ticket',
	'desc_teticketnote' => 'Este evento se activará cuando se añada una nota a un ticket',
	'techangepriority' => 'Cambio Prioridad',
	'desc_techangepriority' => 'Este evento se activará cuando se cambie la prioridad de un ticket',
	'techangestatus' => 'Cambio Estado',
	'desc_techangestatus' => 'Este evento se activará cuando se cambie el estado de un ticket',
	'teassignticket' => 'Asignar Ticket',
	'desc_teassignticket' => 'Este evento se activará cuando se asigne un ticket a alguien del personal',
	'temoveticket' => 'Mover Ticket',
	'desc_temoveticket' => 'Este evento se activará cuando un ticket se mueva a un nuevo departamento',
	'teforwardticket' => 'Reenvío de Ticket',
	'desc_teforwardticket' => 'Este evento se activará cuando un ticket se reenvíe a un tercero',
	'tesavedraft' => 'Guardar como Borrador',
	'desc_tesavedraft' => 'Este evento se activará cuando un ticket se guarde como borrador',
	'teescalateticket' => 'Ticket Priorizado',
	'desc_teescalateticket' => 'Este evento se activará cuando un ticket sea priorizado',
	'tetimeworked' => 'Tiempo Trabajado',
	'desc_timeworked' => 'Este evento se activará cuando un se añada una entrada de tiempo de trabajo al ticket',
	'teticketpost' => 'Respuesta de Ticket Actualizada',
	'desc_teticketpost' => 'Este evento se activará cuando la respuesta a un ticket sea actualizada por el personal',
	'teaddlabel' => 'Etiqueta',
	'desc_teaddlabel' => 'Este evento se activará cuando se añada una etiqueta a un ticket',
	'titleinsertworkflow' => 'Insertado Flujo de trabajo "%s"',
	'msginsertworkflow' => 'Se ha insertado correctamente el flujo de trabajo "%s" en la base de datos.',
	'titleupdateworkflow' => 'Flujo de trabajo actualizado "%s"',
	'msgupdateworkflow' => 'Se ha actualizado correctamente el Flujo de trabajo "%s".',
	'titleworkflowenable' => 'Activados "%d" Flujos de trabajo',
	'msgworkflowenable' => SWIFT_PRODUCT . ' ha activado correctamente los siguientes flujos de trabajo:',
	'titleworkflowdisable' => 'Desactivados "%d" Flujos de Trabajo',
	'msgworkflowdisable' => SWIFT_PRODUCT . ' ha desactivado los siguientes flujos de trabajo:',
	'wfaticketstatus' => 'Cambiar Estado de Ticket',
	'wfatickettype' => 'Cambiar Tipo de Ticket',
	'wfaaddtags' => 'Añadir Etiquetas',
	'wfaremovetags' => 'Eliminar Etiqueta',
	'wfadepartment' => 'Cambiar al Ticket de Departamento',
	'wfaflag' => 'Marcar Ticket',
	'wfaddnotes' => 'Añadir Notas',
	'wfapriority' => 'Cambiar Prioridad de Ticket',
	'wfastaff' => 'Cambiar Propietario del Ticket',
	'wfaslaplan' => 'Cambiar Plan SLA',
	'wfabayesian' => 'Entrenar Bayesiano',
	'wfatrash' => 'Mover a la Papelera',

	// Criteria Tags
	'wftickettype' => 'Tipo de Ticket',
	'desc_wftickettype' => '',
	'wfbayesian' => 'Categoría Bayesiana',
	'desc_wfbayesian' => '',
	'wfsubject' => 'Asunto',
	'desc_wfsubject' => '',
	'notapplicable' => '-- No disponible --',
	'wfticketstatus' => 'Estado Ticket',
	'desc_wfticketstatus' => '',
	'wfticketpriority' => 'Prioridad Ticket',
	'desc_wfticketpriority' => '',
	'wfusergroup' => 'Grupo Usuario',
	'desc_wfusergroup' => '',
	'wfdepartment' => 'Departamento',
	'desc_wfdepartment' => '',
	'wfowner' => 'Propietario',
	'desc_wfowner' => '',
	'wfunassigned' => '-- Sin Asignar --',
	'wfactivestaff' => '-- Personal Activo --',
	'wfemailqueue' => 'Cola Email',
	'desc_wfemailqueue' => '',
	'wfflagtype' => 'Tipo de Marca',
	'desc_wfflagtype' => '',
	'purpleflag' => 'Marca Púrpura',
	'orangeflag' => 'Marca Naranja',
	'greenflag' => 'Marca Verde',
	'yellowflag' => 'Marca Amarilla',
	'redflag' => 'Marca Roja',
	'blueflag' => 'Marca Azul',
	'wfcreator' => 'Creador del Ticket',
	'desc_wfcreator' => '',
	'creatorstaff' => 'Personal',
	'creatorclient' => 'Usuario',
	'wffullname' => 'Nombre',
	'desc_wffullname' => '',
	'wfemail' => 'Email',
	'desc_wfemail' => '',
	'wflastreplier' => 'Último en Responder',
	'desc_wflastreplier' => '',
	'wfcharset' => 'Juego Caracteres',
	'desc_wfcharset' => '',
	'wfslaplan' => 'Plan SLA',
	'desc_wfslaplan' => '',
	'wfdate' => 'Fecha Creación',
	'desc_wfdate' => '',
	'wfdaterange' => 'Fecha Creación <intervalo>',
	'desc_wfdaterange' => '',
	'wflastactivity' => 'Última Publicación',
	'desc_wflastactivity' => '',
	'wflastactivityrange' => 'Última Publicación <intervalo>',
	'desc_wflastactivityrange' => '',
	'wflaststaffreply' => 'Última Respuesta Personal',
	'desc_wflaststaffreply' => '',
	'wflaststaffreplyrange' => 'Última Respuesta Personal <intervalo>',
	'desc_wflaststaffreplyrange' => '',
	'wflastuserreply' => 'Última Respuesta Usuario',
	'desc_wflastuserreply' => '',
	'wflastuserreplyrange' => 'Última Respuesta Usuario <intervalo>',
	'desc_wflastuserreplyrange' => '',
	'wfdue' => 'Fecha Límite',
	'desc_wfdue' => '',
	'wfduerange' => 'Fecha Límite <intervalo>',
	'desc_wfduerange' => '',
	'wfisoverdue' => '¿Vencido?',
	'desc_wfisoverdue' => '',
	'wfresolutiondue' => '¿Vencida fecha Resolución?',
	'desc_wfresolutiondue' => '',
	'wfresolutionduerange' => 'Fecha límite de resolución <intervalo>',
	'desc_wfresolutionduerange' => '',
	'wfisresolutionoverdue' => '¿Sobrepasada la fecha límite?',
	'desc_wfisresolutionoverdue' => '',
	'wftemplategroup' => 'Grupo Plantilla',
	'desc_wftemplategroup' => '',
	'wftimeworked' => 'Tiempo Trabajado (En Minutos)',
	'desc_wftimeworked' => '',
	'wftotalreplies' => 'Respuestas Totales',
	'desc_wftotalreplies' => '',
	'wfpendingfollowups' => 'Seguimientos Pendientes',
	'desc_wfpendingfollowups' => '',
	'wfipaddress' => 'Dirección IP',
	'desc_wfipaddress' => '',
	'wfisemailed' => 'Enviado al Correo',
	'desc_wfisemailed' => '',
	'wfisedited' => 'Editado',
	'desc_wfisedited' => '',
	'wfhasnotes' => 'Con Notas',
	'desc_wfhasnotes' => '',
	'wfhasattachments' => 'Con Adjuntos',
	'desc_wfhasattachments' => '',
	'wfisescalated' => 'Priorizado',
	'desc_wfisescalated' => '',
	'wfhasdraft' => 'Con Borrador',
	'desc_wfhasdraft' => '',
	'wfhasbilling' => 'Con Facturación',
	'desc_wfhasbilling' => '',
	'wfisphonecall' => 'Ticket Telefónico',
	'desc_wfisphonecall' => '',
	'wfislabeled' => 'Etiquetado',
	'desc_wfislabeled' => '',
);
?>