<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array (
	// ======= BEGIN V4 LOCALES =======
	'insertholiday' => 'Insertar Festivo',
	'impex' => 'Importar/Exportar',
	'manageholidays' => 'Festivos',
	'desc_manageholidays' => '',
	'desc_insertholiday' => '',
	'holidaytitle' => 'Título Festividad',
	'desc_holidaytitle' => 'Introduce el título de la Festividad',
	'holidaydate' => 'Fecha Festividad',
	'desc_holidaydate' => 'Por favor, especifica la fecha para esta festividad',
	'tabslaplans' => 'Planes SLA',
	'flagicon' => 'Icono de Marca',
	'desc_flagicon' => 'Especifica la URL del icono de Marca. Las marcas por defecto están ubicadas en el directorio themes/global/flags. Puedes usar las siguientes variables:<br><b>{$themepath}</b> - URL para el directorio de temas<br> - Ejemplo: {$themepath}us.gif',
	'slaplans' => 'Planes SLA Disponibles',
	'slaiscustom' => 'Enlazados con Planes SLA personalizados',
	'desc_slaiscustom' => 'Especifica cuando esta festividad esté enlazada a planes SLA personalizados',
	'customall' => 'Todo',
	'custom' => 'Personalizado',
	'wineditslaholiday' => 'Editar Festividad: %s',
	'editholiday' => 'Editar Festividad',
	'desc_editholiday' => '',
	'invalidslaholiday' => 'Festividad inválida. Por favor, asegúrate de que existe en la base de datos.',
	'titleinsertslaholiday' => 'Festividad Insertada',
	'msginsertslaholiday' => 'Se ha insertado correctamente la Festividad "%s" en la base de datos.',
	'titleupdateslaholiday' => 'Festividad Actualizada',
	'msgupdateslaholiday' => 'Se ha actualizado correctamente la Festividad "%s".',
	'titledelslaholidays' => 'Eliminadas "%d" Festividades',
	'msgdelslaholidays' => 'Se han eliminado correctamente las siguientes festividades de la base de datos:',
	'slaimportexport' => 'Importar/Exportar',
	'desc_slaimportexport' => '',
	'tabexport' => 'Exportar',
	'tabimport' => 'Importar',
	'import' => 'Importar',
	'export' => 'Exportar',
	'exporttitle' => 'Título',
	'desc_exporttitle' => 'Introduce un título para este pack de Festividades',
	'exportauthor' => 'Autor',
	'desc_exportauthor' => 'Autor de este pack de festividades',
	'exportfilename' => 'Archivo',
	'desc_exportfilename' => 'Especifica el nombre de archivo para este pack de Festividades',
	'slaholidaypack' => 'Pack de Vacaciones',
	'slaholidayfile' => 'Archivo Grupo Vacaciones',
	'desc_slaholidayfile' => 'Subir archivo con Pack de Festividades. '.SWIFT_PRODUCT.' importará todas las festividades disponibles en el archivo XML en la base de datos.',
	'titleslaholidayimpex' => 'Pack de Festividades Importado',
	'msgslaholidayimpex' => 'Se ha importado correctamente las <b>"%d"</b> Festividades en la base de datos.',
	'titleslaholidayimpexfailed' => 'La importación del Pack de Festividades ha fallado',
	'msgslaholidayimpexfailed' => 'La importación del Pack de Festividades ha fallado. Por favor, comprueba que el contenido del pack contiene un archivo XML válido generado por '.SWIFT_PRODUCT.'.',
	'insertschedule' => 'Insertar Planificación',
	'desc_insertschedule' => '',
	'sladayopen24' => 'Abierto (24 Horas)',
	'sladayclosed' => 'Cerrado',
	'sladayopencustom' => 'Abierto (Personalizado)',
	'titleinvalidhrange' => 'Intervalo Horario Inválido',
	'msginvalidhrange' => 'Por favor, corrige los siguientes intervalos horarios de la planificación para continuar:',
	'manageschedules' => 'Administrar Planificaciones',
	'desc_manageschedules' => '',
	'titleinsertslasched' => 'Insertar Planificación',
	'msginsertslasched' => 'Se ha insertado correctamente la planificación "%s" en la base de datos.',
	'titleupdateslasched' => 'Planificación Actualizada',
	'msgupdateslasched' => 'Se a actualizado correctamente la planificación "%s".',
	'creationdate' => 'Fecha Creación',
	'invalidslaschedule' => 'Fecha de Creación Inválida. Por favor, asegúrate de que la planificación existe en la base de datos.',
	'editschedule' => 'Editar Planificación',
	'desc_editschedule' => '',
	'titleslaschedulenodel' => 'No se ha podido borrar la Planificación',
	'msgslaschedulenodel' => SWIFT_PRODUCT.' no ha podido borrar las siguientes planificaciones puesto que están enlazas a algunos planes SLA. Por favor, elimina los enlaces para poder borrar el registro de la base de datos.',
	'titledelslaschedules' => 'Eliminadas "%d" Planificaciones',
	'msgdelslaschedules' => 'Se han eliminado correctamente las siguientes planificaciones de la base de datos.',
	'slasettings' => 'Ajustes SLA',
	'tabsettings' => 'Ajustes',
	'sla' => 'SLA',
	'insertplan' => 'Insertar Plan',
	'desc_insertplan' => '',
	'tabholidays' => 'Festividades',
	'plantitle' => 'Título Plan',
	'desc_plantitle' => 'Introduce el Título del Plan.',
	'resolutionduehrs' => 'Fecha Resolution (Horas)',
	'desc_resolutionduehrs' => 'Introduce el número de horas tras los que se espera que el ticket se marque como resuelto.',
	'resolutionduehrs2' => 'Resolución (Horas)',
	'overduehrs' => 'Vencido (Horas)',
	'desc_overduehrs' => 'Introduce el número de horas tras los cuales el ticket se marcará como Vencido. Puedes especificar los minutos como decimales. Ejemplo: 1.20',
	'planschedule' => 'Planificación SLA',
	'desc_planschedule' => 'Especifica la Planificación para este Plan SLA. La fecha de vencimiento se calcula automáticamente en función de la Planificación de trabajo.',
	'smatchtype' => 'Tipo de Coincidencia',
	'matchtype' => 'Opciones de Criterio',
	'desc_matchtype' => 'Selecciona los siguientes métodos de agrupamiento para los campos de criterio.',
	'smatchall' => 'Coincidir Todo (AND)',
	'smatchany' => 'Coincidir Cualquiera (OR)',
	'isenabled' => '¿Activo?',
	'desc_isenabled' => 'Conmuta la ejecución de este plan SLA activando/desactivando esta opción.',
	'sortorder' => 'Orden',
	'desc_sortorder' => 'Especifica el orden para esta regla. Las reglas siempre se procesan en orden ascendente.',
	'insertcriteria' => 'Insertar Criterio',
	'manageplans' => 'Planes',
	'schedules' => 'Planificaciones',
	'desc_manageplans' => '',
	'scheduletitle' => 'Título Planificación',
	'desc_scheduletitle' => '',
	'titlenocriteriaadded' => 'No hay Criterios Disponibles',
	'msgnocriteriaadded' => 'Necesitas añadir al menos un criterio para insertar/editar el plan SLA.',
	'noscheduleavailable' => '-- Sin Planificaciones Disponibles --',
	'titlenoslasched' => 'Planificación SLA no disponible',
	'msgnoslasched' => 'No hay Planificaciones SLA añadidas en '. SWIFT_PRODUCT .'. Necesitas añadir una Planificación a SLA para insertar/actualizar un plan SLA en el sistema.',
	'nocustomholidays' => 'No hay festividades personalizadas disponibles. Puedes activar esta propiedad en Administrar Festividades &gt; Editar',
	'editplan' => 'Editar Plan',
	'desc_editplan' => '',
	'invalidslaplan' => 'Plan SLA Inválido. Asegúrate de que el Plan SLA existe en la base de datos.',
	'titleslaplandel' => 'Eliminados "%d" Planes SLA',
	'msgslaplandel' => 'Se han eliminado los siguientes Planes SLA de la base de datos:',
	'titleslaplanenable' => 'Activados Planes SLA "%d"',
	'msgslaplanenable' => 'Se han activado los siguientes Planes SLA:',
	'titleslaplandisable' => 'Desactivados "%d" Planes SLA',
	'msgslaplandisable' => 'Se han desactivado correctamente los siguientes Planes SLA:',
	'linkedholidays' => 'Festividades Enlazadas (Personalizado)',
	'titleslaplaninsert' => 'Insertado Plan SLA',
	'msgslaplaninsert' => 'Se ha insertado correctamente el plan SLA "%s" en la base de datos.',
	'titleslaplanupdate' => 'Plan SLA Actualizado',
	'msgslaplanupdate' => 'Se ha actualizado correctamente el plan SLA "%s".',
	'if' => 'If',
	'scheduledesc' => 'Información Planificación',

	// SLA Rules
	'srticketstatus' => 'Estado Ticket',
	'desc_srticketstatus' => '',
	'srticketpriority' => 'Prioridad Ticket',
	'desc_srticketpriority' => '',
	'srdepartmentid' => 'Departamento',
	'desc_srdepartmentid' => '',
	'srownerstaffid' => 'Propietario Ticket',
	'desc_srownerstaffid' => '',
	'sremailqueueid' => 'Cola Email',
	'srusergroupid' => 'Grupo Usuario',
	'desc_srusergroupid' => '',
	'desc_sremailqueueid' => '',
	'notapplicable' => '-- SA --',
	'srfullname' => 'Nombre',
	'desc_srfullname' => '',
	'sremail' => 'Email',
	'desc_sremail' => '',
	'srlastreplier' => 'Última Respuesta',
	'desc_srlastreplier' => '',
	'srsubject' => 'Asunto',
	'desc_srsubject' => '',
	'srcharset' => 'Juego Caracteres',
	'desc_srcharset' => '',
	'srflagtype' => 'Tipo Marca',
	'desc_srflagtype' => '',
	'srbayescategory' => 'Categoría Bayesiana',
	'desc_srbayescategory' => '',
	'purpleflag' => 'Marca Púrpura',
	'redflag' => 'Marca Roja',
	'orangeflag' => 'Marca Naranja',
	'yellowflag' => 'Marca Amarilla',
	'blueflag' => 'Marca Azul',
	'greenflag' => 'Marca Verde',
	'srcreator' => 'Creador',
	'desc_srcreator' => '',
	'creatorstaff' => 'Personal',
	'creatorclient' => 'Usuario',
	'srunassigned' => '-- Sin Asignar --',
	'srtemplategroup' => 'Grupo Plantilla',
	'desc_srtemplategroup' => '',
	'srisresolved' => '¿Resuelto?',
	'desc_srisresolved' => '',
	'srtickettype' => 'Tipo Ticket',
	'desc_srtickettype' => '',
	'srwasreopened' => '¿Reabierto?',
	'desc_srwasreopened' => '',
	'srtotalreplies' => 'Respuestas Totales',
	'desc_srtotalreplies' => '',


	'slajanuary' => 'Enero (01)',
	'slafebruary' => 'Febrero (02)',
	'slamarch' => 'Marzo (03)',
	'slaapril' => 'Abril (04)',
	'slamay' => 'Mayo (05)',
	'slajune' => 'Junio (06)',
	'slajuly' => 'Julio (07)',
	'slaaugust' => 'Agosto (08)',
	'slaseptember' => 'Septiembre (09)',
	'slaoctober' => 'Octubre (10)',
	'slanovember' => 'Noviembre (11)',
	'sladecember' => 'Deciembre (12)',
	// ======= END V4 LOCALES =======
);
?>