<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array (
	// ======= BEGIN v4 LOCALES =======
	'lrskills' => 'Especialidades',
	'lrrules' => 'Reglas Visitante',
	'lrgroups' => 'Grupos Visitantes',
	'lrbans' => 'Bloqueos Visitantes',
	'lrmessagerouting' => 'Enrutado de Mensajes',
	'corestaff' => 'Personal',
	'coreteams' => 'Equipos',
	'admin_tmpcanpersonalize' => 'Puede Acceder a la Plantilla > Personalizar',
	'coreloginshare' => 'LoginShare Personal',
	'coredepartments' => 'Departamentos',
	'coretemplategroups' => 'Grupos Plantilla',
	'coretemplates' => 'Plantillas',
	'coreusergroups' => 'Grupos Usuarios',
	'staff_profile' => 'Puede Actualizar el Perfil',
	'staff_changepassword' => 'Puede cambiar contraseña',
	'coretemplateloginshare' => 'LoginShare Usuarios',
	'corecustomfieldgroups' => 'Campos de Grupo Personalizados',
	'corecustomfields' => 'Campos Personalizados',
	'staff_newssubscribers' => 'Subscriptores de Noticias',
	'staff_newscategories' => 'Categorías Noticias',
	'staff_newscanpublicinsert' => 'Puede insertar Noticias Públicas',
	'staff_newsitems' => 'Noticias',
	'staff_troubleshootercategories' => 'Categorías',
	'corewidgets' => 'Widgets',
	'corelanguages' => 'Idiomas',
	'staff_comments' => 'Comentarios',
	'corelanguagephrases' => 'Frases Idiomas',
	'livechatcalls' => 'Llamadas',
	'parserqueues' => 'Colas de Correo',
	'admin_tcanrunmoveattachments' => 'Puede Mover Adjuntos',
	'staff_troubleshootersteps' => 'Pasos',
	'parserlogs' => 'Registro Procesador',
	'parserrules' => 'Reglas Procesador',
	'parserbreaklines' => 'Saltos de Líneas',
	'parserbans' => 'Bloqueos',
	'parsercatchall' => 'Reglas Recoge-Todo',
	'admin_canrunimport' => 'Puede Ejecutar Importaciones',
	'parserblockages' => 'Bloqueos de Bucles',
	'parserlooprule' => 'Reglas Bucles',
	'issuestatus' => 'Estados',
	'issuepriorities' => 'Prioridades',
	'issueresolutions' => 'Resoluciones',
	'issuelinks' => 'Enlaces',
	'issuetypes' => 'Tipos',
	'ticketworkflows' => 'Flujos',
	'ticketstatuses' => 'Estados',
	'ticketpriorities' => 'Prioridades',
	'ticketfiletypes' => 'Tipos Archivos',
	'staff_notifications' => 'Notificaciones',
	'tickettypes' => 'Tipos de Tickets',
	'ticketlinks' => 'Enlaces',
	'ticketbayes' => 'Categorías Bayesianas',
	'ticketslaplans' => 'Planes SLA',
	'ticketslaschedules' => 'Calendarios SLA',
	'staff_ticketbilling' => 'Facturación Ticket',
	'staff_tcanforward' => 'Puede Reenviar Ticket',
	'staff_tcanreply' => 'Puede Responder Ticket',
	'staff_tcanfollowup' => 'Puede Crear Seguimientos',
	'staff_tcanrelease' => 'Puede Liberar Ticket',
	'staff_ticketfollowup' => 'Seguimientos',
	'staff_tcanviewauditlog' => 'Puede Ver Registros de Auditoría',
	'staff_ticketnotes' => 'Notas en Ticket',
	'staff_tcanworkflow' => 'Puede Ver/Actualizar Flujos',
	'staff_tcansaveasdraft' => 'Puede Guardar Borradores',
	'staff_tcanbenchmarks' => 'Puede Ver Valoraciones',
	'ticketslaholidays' => 'Vacaciones SLA',
	'ticketescalations' => 'Escalas',
	'corebenchmarks' => 'Valoraciones',
	'corescheduledtasks' => 'Tareas Programadas',
	'staff_usernotes' => 'Notas Usuarios',
	'livechatnotes' => 'Notas Chat',
	'livechatmessages' => 'Mensajes/Cuestionarios',
	'livechatcanned' => 'Enlatado',
	'livechathistory' => 'Historial Chat',
	'winapplrbans' => 'Winapp: Bloqueos Visitantes',
	'staff_kbcategories' => 'Categorías',
	'staff_kbarticles' => 'Artículos',
	'staff_kbcaninsertpublishedarticles' => 'Puede Publicar Artículos',
	'staff_trcaninsertpublishedsteps' => 'Puede Publicar Pasos',
	'staff_tags' => 'Etiquetas',
	'staff_tcansearch' => 'Puede Buscar Tickets',
	'staff_ticketmacros' => 'Macros',
	'staff_ticketfilters' => 'Filtros',
	'staff_ticketviews' => 'Visitas',
	'staff_tickets' => 'Tickets',
	'staff_ticketposts' => 'Mensajes Ticket',
	'staff_tcanmarkasspam' => '¿Puede marcar el ticket como spam?',
	'staff_tcantrashticket' => '¿Puede borrar tickets?',
	'ls_canobserve' => 'Winapp: Puede Observar Chats',
	'admin_canmanagetaggenerator' => 'Puede Administrar el Generador de Etiquetas',
	'admin_canmanagerestapi' => 'Puede Administrar REST API',
	'admin_canviewloginlog' => 'Puede Ver el Registro de Identificación',
	'admin_canviewactivitylog' => 'Puede ver el Registro de Actividad',
	'admin_canviewerrorlog' => 'Puede Ver el Registro de Errores',
	'admin_canviewdatabase' => 'Puede Ver los Detalles de la Base de Datos',
	'admin_canrundiagnostics' => 'Puede Ejecutar Diagnósticos',
	'admin_canviewdepartments' => 'Puede Ver Departamentos',
	'admin_lrcandeletevisitorgroup' => 'Puede Borrar Grupos Visitantes',
	'admin_lrcaninsertvisitorgroup' => 'Puede Insertar Grupos Visitantes',
	'admin_lrcanupdatevisitorgroup' => 'Puede Actualizar Grupos Visitantes',
	'admin_lrcanviewvisitorgroups' => 'Puede Ver Grupos Visitantes',
	'admin_caninsertstaff' => 'Puede Insertar Usuarios de Plantilla',
	'admin_caneditstaff' => 'Puede Actualizar Usuarios de Plantilla',
	'admin_candeletestaff' => 'Puede Borrar Usuarios de Plantilla',
	'admin_caninsertteams' => 'Puede Insertar Equipos',
	'admin_caneditteams' => 'Puede Actualizar Equipos',
	'admin_candeleteteams' => 'Puede Borrar Equipos',
	'admin_caninsertdepartment' => 'Puede Insertar Departamentos',
	'admin_caneditdepartment' => 'Puede Editar Departamentos',
	'admin_candeletedepartment' => 'Puede Borrar Departamentos',
	'admin_canupdatesettings' => 'Puede Actualizar Ajustes',
	'admin_canrebuildgeoip' => 'Puede Reconstruir la Base de Datos GeoIP',
	'admin_caninsertcfgroup' => 'Can Insertar Campos de Grupo Personalizados',
	'admin_canupdatecfgroup' => 'Puede Actualizar Campos de Grupo Personalizados',
	'admin_candeletecfgroup' => 'Puede Borrar Campos de Grupo Personalizados',
	'admin_caninsertcustomfield' => 'Puede Insertar Campos Personalizados',
	'admin_canupdatecustomfield' => 'Puede Actualizar Campos Personalizados',
	'admin_candeletecustomfield' => 'Puede Borrar Campos Personalizados',
	'admin_canviewlanguages' => 'Puede Ver Idioma',
	'admin_caninsertlanguage' => 'Puede Insertar Idiomas',
	'admin_canupdatelanguage' => 'Puede Actualizar Idiomas',
	'admin_candeletelanguage' => 'Puede Borrar Idiomas',
	'admin_canrestorelanguage' => 'Puede Restaurar Idiomas',
	'admin_canviewphrases' => 'Puede Ver Frases',
	'admin_caninsertphrase' => 'Puede Insertar Frases',
	'admin_canupdatephrase' => 'Puede Actualizar Frases',
	'admin_candeletephrase' => 'Puede Borrar Frases',
	'admin_canimportphrases' => 'Puede Importar Packs de Idiomas',
	'admin_canexportphrases' => 'Puede Exportar Packs de Idiomas',
	'admin_canrestorephrases' => 'Puede Restaurar Frases',
	'admin_canrunlanguagediagnostics' => 'Puede Ejecutar Diagnósticos de Idiomas',
	'mod_ringroute' => 'RingRoute',
	'admin_canupdaterrprofiles' => 'Puede Actualizar Perfiles de RingRoute',
	'admin_lrcanviewonlinestaff' => 'Puede Ver Personal Online',
	'admin_lrcandisconnectstaff' => 'Puede Desconectar Personal Online',
	'admin_lrcanupdaterouting' => 'Puede Actualizar Reglas de Enrutamiento de Mensajes',
	'admin_lrcanviewrouting' => 'Puede Ver Reglas de Enrutamiento de Mensajes',
	'admin_lrcanviewbans' => 'Puede Ver Bloqueos de IP',
	'admin_lrcaninsertban' => 'Puede Insertar Bloqueos de IP',
	'admin_lrcanupdateban' => 'Puede Actualizar Bloqueos de IP',
	'admin_lrcandeleteban' => 'Puede Borrar Bloqueos de IP',
	'admin_lrcanviewrules' => 'Puede Ver Reglas de Visitantes',
	'admin_lrcaninsertrule' => 'Puede Insertar Reglas de Visitantes',
	'admin_lrcanupdaterule' => 'Puede Actualizar Reglas de Visitantes',
	'admin_lrcandeleterule' => 'Puede Borrar Reglas de Visitantes',
	'admin_lrcanviewskills' => 'Puede Ver Especialidades',
	'admin_lrcaninsertskill' => 'Puede Insertar Especialidades',
	'admin_lrcanupdateskill' => 'Puede Actualizar Especialidades',
	'admin_lrcandeleteskill' => 'Puede Borrar Especialidades',
	'admin_mpcaninsertqueue' => 'Puede Insertar Cola de Correo',
	'admin_mpcanupdatequeue' => 'Puede Actualizar Cola de Correo',
	'admin_mpcandeletequeue' => 'Pude Borrar Cola de Correo',
	'admin_mpcanviewqueues' => 'Puede Ver Colas de Correo',
	'admin_mpcanviewparserlogs' => 'Puede Ver el Procesador de Registros',
	'admin_mpcandeleteparserlogs' => 'Puede Borrar el Procesador de Registros',
	'mod_parser' => 'Procesador de Correo',
	'admin_mpcaninsertrule' => 'Puede Insertar Reglas',
	'admin_mpcanupdaterule' => 'Puede Actualizar Reglas',
	'admin_mpcandeleterule' => 'Puede Borrar Reglas',
	'admin_mpcanviewrules' => 'Puede Ver Reglas',
	'admin_mpcaninsertbreakline' => 'Puede Insertar Salto de Línea',
	'admin_mpcanupdatebreakline' => 'Puede Actualizar Salto de Línea',
	'admin_mpcandeletebreaklines' => 'Puede Borrar Salto de Línea',
	'admin_mpcanviewbreaklines' => 'Puede Ver Saltos de Línea',
	'admin_mpcaninsertban' => 'Puede Insertar Bloqueo de Email',
	'admin_mpcanupdateban' => 'Puede Actualizar Bloqueo de Email',
	'admin_mpcandeletebans' => 'Puede Borrar Bloqueo de Email',
	'admin_mpcanviewbans' => 'Puede Ver Bloqueos de Email',
	'admin_mpcaninsertcatchall' => 'Puede Insertar Reglas Recoge-Todo',
	'admin_mpcanupdatecatchall' => 'Puede Actualizar Reglas Recoge-Todo',
	'admin_candeletecatchall' => 'Puede Borrar Reglas Recoge-Todo',
	'admin_canviewcatchall' => 'Puede Ver Reglas Recoge-Todo',
	'admin_iscanviewstatus' => 'Puede Ver Estado',
	'admin_iscaninsertstatus' => 'Puede Insertar Estados',
	'admin_iscanupdatestatus' => 'Puede Actualizar Estados',
	'admin_iscandeletestatus' => 'Puede Borrar Estados',
	'admin_iscanviewpriorities' => 'Puede Ver Prioridades',
	'admin_iscaninsertpriority' => 'Puede Insertar Prioridades',
	'admin_iscanupdatepriority' => 'Puede Actualizar Prioridades',
	'admin_iscandeletepriorities' => 'Puede Borrar Prioridades',
	'admin_iscanviewresolutions' => 'Puede Ver Resoluciones',
	'admin_iscaninsertresolution' => 'Puede Insertar Resoluciones',
	'admin_iscanupdateresolution' => 'Puede Actualizar Resoluciones',
	'admin_iscandeleteresolutions' => 'Puede Borrar Resoluciones',
	'admin_iscanviewlinks' => 'Puede Ver Enlaces',
	'admin_iscaninsertlink' => 'Puede Insertar Enlaces',
	'admin_iscanupdatelink' => 'Puede Actualizar Enlaces',
	'admin_iscandeletelinks' => 'Puede Borrar Enlaces',
	'admin_iscanviewtypes' => 'Puede Ve Tipos',
	'admin_iscaninsertype' => 'Puede Insertar Tipos',
	'admin_iscanupdatetype' => 'Puede Actualizar Tipos',
	'admin_iscandeletetypes' => 'Puede Borrar Tipos',
	'mod_issues' => 'Problemas',
	'mod_tickets' => 'Tickets',
	'admin_tcanviewbayescategories' => 'Puede Ver Categorías Bayesianas',
	'admin_tcandeletebayescategories' => 'Puede Borrar Categorías Bayesianas',
	'admin_tcaninsertbayescategory' => 'Puede Insertar Categorías Bayesianas',
	'admin_tcanupdatebayescategory' => 'Puede Actualizar Categorías Bayesianas',
	'admin_tcanrunbayesdiagnostics' => 'Puede Ejecutar Diagnósticos Bayesianos',
	'admin_tcanviewslaplans' => 'Puede Ver Planes SLA',
	'admin_tcaninsertslaplan' => 'Puede Insertar Planes SLA',
	'admin_tcanupdateslaplan' => 'Puede Actualizar Planes SLA',
	'admin_tcandeleteslaplans' => 'Puede Borrar Planes SLA',
	'admin_tcanviewslaschedules' => 'Puede Ver Planificaciones SLA',
	'admin_tcaninsertslaschedules' => 'Puede Insertar Planificaciones SLA',
	'admin_tcanupdateslaschedules' => 'Puede Actualizar Planificaciones SLA',
	'admin_tcandeleteslaschedules' => 'Puede Borrar Planificaciones SLA',
	'admin_tcanviewslaholidays' => 'Puede Ver Festivos SLA',
	'admin_tcaninsertslaholidays' => 'Puede Insertar Festivos SLA',
	'admin_tcanupdateslaholidays' => 'Puede Actualizar Festivos SLA',
	'admin_tcandeleteslaholidays' => 'Puede Borrar Festivos SLA',
	'admin_tcanimpexslaholidays' => 'Puede Importar/Exportar Vacaiones SLA',
	'admin_tcanviewescalations' => 'Puede Ver Reglas de Escalado',
	'admin_tcaninsertescalations' => 'Puede Insertar Reglas de Escalado',
	'admin_tcanupdateescalations' => 'Puede Actualizar Reglas Escalado',
	'admin_tcandeleteescalations' => 'Puede Borrar Reglas Escalado',
	'admin_canviewcfgroups' => 'Puede Ver Campos Personalizados de Grupos',
	'admin_canviewcfields' => 'Puede Ver Campos Personalizados',
	'admin_tmpcanviewgroups' => 'Puede Ver Grupos de Plantillas',
	'admin_tmpcaninsertgroup' => 'Puede Insertar Grupos de Plantilla',
	'admin_tmpcanupdategroup' => 'Puede Actualizar Grupos de Plantillas',
	'admin_tmpcandeletegroup' => 'Puede Borrar Grupos de Plantillas',
	'admin_tmpcanviewtemplates' => 'Puede Ver Plantillas',
	'admin_tmpcaninserttemplate' => 'Puede Insertar Plantillas',
	'admin_tmpcanrestoretemplates' => 'Puede Restaurar Plantillas',
	'admin_tmpcanupdatetemplate' => 'Puede Actualizar Plantillas',
	'admin_tmpcanrundiagnostics' => 'Puede Ejecutar Diagnósticos de Plantillas',
	'admin_tmpcanrunimportexport' => 'Puede Ejecutar Importar/Exportar',
	'admin_tmpcanimportloginshare' => 'Puede Importar el Plugin LoginShare',
	'admin_tmpcanupdateloginshare' => 'Puede Actualizar Ajustes de LoginShare',
	'admin_tmpcanviewloginshare' => 'Puede Ver Plugins LoginShare',
	'admin_tmpcansearchtemplates' => 'Puede Buscar Plantillas',
	'admin_tmpcandeleteloginshare' => 'Puede Borrar Plugins LoginShare',
	'admin_tcanviewworkflows' => 'Puede Ver Flujos',
	'admin_tcaninsertworkflow' => 'Puede Insertar Flujos',
	'admin_tcanupdateworkflow' => 'Puede Actualizar Flujos',
	'admin_tcandeleteworkflows' => 'Puede Borrar Flujos',
	'admin_tcanviewstatus' => 'Can Ver Estado',
	'admin_tcaninsertstatus' => 'Puede Insertar Estado',
	'admin_tcanupdatestatus' => 'Puede Actualizar Estado',
	'admin_tcandeletestatus' => 'Puede Borrar Estado',
	'admin_tcanviewpriorities' => 'Puede Ver Prioridades',
	'admin_tcaninsertpriority' => 'Puede Insertar Prioridades',
	'admin_tcanupdatepriority' => 'Puede Actualizar Prioridades',
	'admin_tcandeletepriority' => 'Puede Borrar Prioridades',
	'admin_tcanviewfiletypes' => 'Puede Ver Tipos de Archivos',
	'admin_tcaninsertfiletype' => 'Puede Insertar Tipos de Archivos',
	'admin_tcanupdatefiletype' => 'Puede Actualizar Tipos de Archivos',
	'admin_tcandeletefiletypes' => 'Puede Borrar Tipos de Archivo',
	'admin_tcanviewlinks' => 'Puede Ver Enlaces',
	'admin_tcaninsertlink' => 'Puede Insertar Enlaces',
	'admin_tcanupdatelink' => 'Puede Actualizar Enlaces',
	'admin_tcandeletelinks' => 'Puede Borrar Enlaces',
	'admin_tcanpurgeattachments' => 'Puede Purgar Adjuntos',
	'admin_tcanrunmaintenance' => 'Puede Ejecutar Mantenimiento de Tickets',
	'admin_mpcanviewloopblockages' => 'Puede Ver Bloqueos de Bucles',
	'admin_mpcandeleteloopblockages' => 'Puede Borrar Bloqueos de Bucles',
	'admin_mpcanviewlooprules' => 'Puede Ver Reglas de Bucles',
	'admin_mpcaninsertlooprule' => 'Puede Insertar Reglas de Bucles',
	'admin_mpcanupdatelooprule' => 'Puede Actualizar Reglas de Bucles',
	'admin_mpcandeletelooprule' => 'Puede Borrar Reglas de Bucles',
	'staff_users' => 'Usuarios',
	'staff_usersorganizations' => 'Organizaciones Usuarios',
	// ======= END v4 LOCALES =======

	/**
	* ###############################################
	* DEPARTMENT PERMISSIONS
	* ###############################################
	*/
	'd_ls_canhistory' => 'Puede Ver el Historial de Transcripciones de Chat',
	'd_ls_canchat' => 'Puede Aceptar/Rechazar Chats',
	'd_t_canreply' => 'Puede Responder Tickets',
	'd_t_canforward' => 'Puede Reenviar Tickets',
	'd_t_canfollowup' => 'Puede Crear Tickets de Seguimiento',
	'd_t_canbilling' => 'Puede Crear Entradas de Facturación',


	/**
	* ###############################################
	* TEAM PERMISSIONS
	* ###############################################
	*/
	// Troubleshooter Permissions
	'mod_troubleshooter' => 'Asistente de Problemas',
	'tr_entab' => 'Puede Ver la Pestaña del Asistente',
	'tsmanagecategories' => 'Puede Administrar Categorías',
	'tsmanagesteps' => 'Puede Administrar Pasos',
	'tsinsertcategory' => 'Puede Insertar Categoría',
	'tseditcategory' => 'Puede Editar Categoría',
	'tsdeletecategory' => 'Puede Borrar Categoría',
	'tsaddstep' => 'Puede Añadir Pasos en el Asistente',
	'tseditstep' => 'Puede Editar un Paso Existente',
	'tsdeletestep' => 'Puede Borrar Paso de Asistente',
	'tsexport' => 'Puede Exportar Datos de Asistente',
	'tsimport' => 'Puede Importar Datos Asistente',

	// Tickets
	'mod_tickets' => 'Tickets',
	't_entab' => 'Puede Ver Pestaña de Tickets',
	'tmanage' => 'Puede Administrar Tickets',
	'tdeleteview' => 'Puede Borrar Visitas de Tickets',
	'teditview' => 'Puede Editar Vistas de Tickets',
	'tnewticket' => 'Puede Crear un Nuevo Ticket',
	'tdeleteticket' => 'Puede Borrar Tickets',
	'tdeletepost' => 'Puede Borrar Mensajes del Ticket',
	'teditpost' => 'Puede Editar Mensajes del Ticket',
	'texport' => 'Puede Exportar como PDF/XML',
	'tforward' => 'Puede Reenviar Tickets',
	'tcrearule' => 'Puede Crear Reglas de Alerta Públicas',
	'tbilling' => 'Puede Añadir Entradas de Facturación',
	'tdelrecipients' => 'Puede Borrar Destinatarios de Ticket',
	'tmerge' => 'Puede Unificar Tickets',
	'tdelarule' => 'Puede Borrar Reglas de Alerta Públicas',
	'tupdarule' => 'Puede Editar Reglas de Alerta Públicas',
	'tdellabel' => 'Puede Borrar Etiquetas de Ticket',
	'tcanviewall' => 'Puede Ver Todos los Tickets <i>Sin Asignar, Asignados a sí mismo y asignados a Otros)</i>',
	'tbanticket' => 'Puede Bloquear Usuarios',
	'tbandelete' => 'Puede Bloquear Usuarios y Borrar Tickets',

	// Downloads
	'mod_downloads' => 'Descargas',
	'dl_entab' => 'Puede Ver la Pestaña de Descargas',
	'dlcandelcat' => 'Puede Borrar Categorías',
	'dlcaneditcat' => 'Puede Editar Categorías',
	'dlcandelfile' => 'Puede Borrar Archivo',
	'dlcaneditfile' => 'Puede Editar Archivo',
	'dlcaninsertcat' => 'Puede Insertar Categoría',
	'dlcaninsertfile' => 'Puede Insertar Archivo',

	// News
	'mod_news' => 'Novedades',
	'nw_entab' => 'Puede Ver la Pestaña de Noticias / Novedades',

	// Knowledgebase
	'mod_knowledgebase' => 'Documentación',
	'kb_entab' => 'Puede Ver la Pestaña de Documentación',

	// Teamwork
	'mod_teamwork' => 'Equipo',
	'tw_entab' => 'Puede Ver la Pestaña de Equipo',

	// Live Chat
	'mod_livesupport' => 'Live Chat',
	'ls_entab' => 'Puede Ver la Pestaña Live Chat',

	// Core
	'mod_core' => 'SWIFT General',
	'cu_entab' => 'Puede Ver la Pestaña de Usuarios',
);

?>