<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array (
	// ======= BEGIN NEW V4 LOCALES =======
	'tabgeneral' => 'General',
	'insertcfgrouptitle' => 'Insertado Grupo de Campo Personalizado "%s"',
	'insertcfgroupmsg' => 'Se ha insertado correctamente el siguiente grupo de campo  personalizado "<b>%s</b>" en la base de datos.<br><b>Título:</b> %s<br><b>Tipo:</b> %s<br><b>Orden de Visualización:</b> %s',
	'updatecfgrouptitle' => 'Actualizado Grupo de Campo Personalizado "%s"',
	'updatecfgroupmsg' => 'Se ha actualizado correctamente el grupo de campo personalizado "<b>%s</b>".<br><b>Título:</b> %s<br><b>Tipo:</b> %s<br><b>Orden de Visualización:</b> %s',
	'wineditcfgroup' => 'Editar Grupo de Campo  Personalizado: %s',
	'titledelcfgroup' => 'Eliminados "%d" Grupos de Campo Personalizado',
	'msgdelcfgroup' => 'Se han eliminado correctamente los siguientes grupos de campo personalizados de la base de datos:<br>%s',
	'buttonnext' => 'Siguiente',
	'encryptindb' => 'Encriptar valor en la base de datos',
	'desc_encryptindb' => 'Si se activa, el valor almacenado en la base de datos se encriptará usando un hash único de instalación. Los valores de los campos de contraseña se encriptan por defecto.',
	'tabdepartments' => 'Departamentos',
	'assigneddepartments' => 'Departamentos Asignados',
	'titleunproc' => 'No se pudo procesar',
	'msgunproc' => 'Necesitas crear al menos un grupo de campo personalizado para añadir un nuevo campo personalizado.',
	'taboptions' => 'Opciones',
	'tablanguages' => 'Idiomas: Traducción',
	'tabpermissions' => 'Permisos',
	'field_date' => 'Fecha',
	'desc_field_date' => 'Este tipo de campo permite crear un campo con un selector de fecha.',
	'field_linkedselect' => 'Selección de enlazados',
	'desc_field_linkedselect' => 'Selecciona este tipo de campo para crear una casilla de Selección Enlazados',
	'cfteampermissions' => 'Permisos: Equipo',
	'cfstaffpermissions' => 'Permisos: Personal (Sobreescribe los permisos de Equipo)',
	'notset' => 'Sin definir',
	'insertcfieldtitle' => 'Insertados los Campos Personalizados "%s"',
	'insertcfieldmsg' => 'Se han insertado correctamente los campos personalizados "<b>%s</b>" en la base de datos.<br>',
	'updatecfieldtitle' => 'Actualizado Campo Personalizado "%s"',
	'updatecfieldmsg' => 'Se ha actualizado correctamente el campo personalizado "<b>%s</b>".<br>',
	'wineditcfield' => 'Editar Campo Personalizado: %s',
	'titledelcfields' => 'Eliminados "%d" Campos Personalizados',
	'msgdelcfields' => 'Se han eliminado correctamente los siguientes campos personalizados de la base de datos:<br>%s',
	// ======= END NEW V4 LOCALES =======

	'grouptitle' => 'Título del Grupo',
	'desc_grouptitle' => '',
	'grouptype' => 'Tipo de Grupo',
	'desc_grouptype' => 'Los campos personalizados deben pertenecer a un <b>grupo de campo personalizado</b>, que queda ligado a un área del producto, como creación de ticket, chat, usuarios, grupos de usuarios, etc.',
	'displayorder' => 'Orden de Visualización',
	'desc_displayorder' => 'Si hay múltiples grupos en un área, se ordenarán usando el orden (ascendente) especificado aquí.',
	'customfields' => 'Campos Personalizados',
	'managegroups' => 'Administrar Grupos',
	'desc_customfieldgroups' => '',
	'grouplist' => 'Grupos de Campos Personalizados',
	'insertgroup' => 'Insertar Grupo',
	'cfgroupdetails' => 'Detalles del grupo de Campo Personalizado',
	'grouptypeuser' => 'Ususario',
	'grouptypeknowledgebase' => 'Documentación',
	'grouptypenews' => 'Artículos de Noicias',
	'grouptypetroubleshooter' => 'Pasos del Asistente de problemas',
	'grouptypedownloads' => 'Descargar Archivos',
	'grouptypeuserorganization' => 'Organización de Usuario',
	'grouptypestaffticket' => 'Creación de Ticket de Personal',
	'grouptypeuserticket' => 'Creación de Ticket de Usuario',
	'grouptypestaffuserticket' => 'Creación de Ticket de Administración y Usuario',//Mahesh Slaria: Staff & user ticket creation
	'grouptypetimetrack' => 'Registro de Tiempo de Ticket',
	'grouptypecontact' => 'Contacto de Equipo',
	'grouptypeevent' => 'Evento de Equipo',
	'grouptypetask' => 'Tarea de Equipo',
	'grouptypelivesupportpre' => 'Live Chat - Pre Chat',
	'grouptypelivesupportpost' => 'Live Chat - Post Chat',
	'insertgroup' => 'Insertar Grupo',
	'updategroup' => 'Actualizar Grupo',
	'cfgroupinsertconfirm' => 'Grupo de campo personalizado "%s" correctamente insertado',
	'addfield' => 'Añadir Campo',
	'cfgroupdelconfirm' => 'Grupo de campo personalizado correctamente eliminado',
	'cfgroupactconfirm' => '¿Seguro que quieres borrar este grupo de campo personalizado? Al borrar un grupo resultarás en la eliminación permanente de todos los campos personalizados y todos sus correspondientes valores almacenados. Esta acción es irreversible',
	'editgroup' => 'Editar Grupo',
	'invalidcfgroup' => 'Grupo de campo personalizado inválido',
	'usergroups' => 'Grupos de Usuario',
	'desc_usergroups' => 'Selecciona el grupo de usuarios para el que el grupo de campo personalizado debería estar disponible. Por ejemplo, puedes tener dos grupos de usuarios diferentes y puedes querer tener estos campos personalizados únicamente disponibles para uno de ellos.',
	'cfgroupupdateconfirm' => 'Grupo de campo personalizado "%s" correctamente actualizado',
	'selectoneusergroup' => 'ERROR: Necesitas seleccionar al menos un grupo de usuario',
	'insertfield' => 'Campo Insertado',
	'desc_customfields' => '',
	'next' => 'Siguiente &raquo;',
	'selectcftype' => 'Selecciona el Tipo de Campo Personalizado',
	'insertfieldstep1' => 'Insertar Campo: Paso 1',
	'insertfieldstep2' => 'Insertar Campo: Paso 2',
	'fielddetails' => 'Detalles del Campo',
	'customfieldgroup' => 'Grupo de Campo Personalizado',
	'desc_customfieldgroup' => '',
	'fieldtype' => 'Tipo de Campo',
	'erroraddcfgroup' => 'ERROR: Necesitas crear al menos un grupo de campo personalizado para añadir un campo personalizado',
	'nogroupadded' => '-- Sin Grupo de Campo Personalizado Disponible --',
	'fieldtitle' => 'Título del Campo',
	'desc_fieldtitle' => 'El título del campo mostrado junto a cada campo en las interfaces de usuario y personal para describir para qué sirve cada campo.',
	'fieldname' => 'Nombre del Campo',
	'desc_fieldname' => '',
	'isrequired' => '¿Obligatorio?',
	'desc_isrequired' => 'Define si este campo es o no obligatorio. Si se activa, el usuario se verá obligado a completar se campo para poder procesar sus datos.',
	'usereditable' => 'Modificable por el usuario',
	'desc_usereditable' => 'Define si el usuario podrá modificar o no la información del campo',
	'staffeditable' => 'Modificable por Personal',
	'desc_staffeditable' => 'Define si el personal podrá o no modificar la información el campo',
	'regexpvalidate' => 'Validación de Expresión Regular',
	'desc_regexpvalidate' => 'Aquí puedes especificar una expresión regular para validar el campo de entrada.',
	'defaultvalue' => 'Valor por defecto',
	'desc_defaultvalue' => 'Si se especifica, el valor por defecto del campo quedará definido al valor indicado aquí.',
	'description' => 'Descripción del Campo',
	'desc_description' => 'Una descripción para el campo.',
	'fielddisplayorder' => 'Orden de visualización',
	'desc_fielddisplayorder' => 'Si hay múltiples campos dentro de un grupo, se ordenarán usando el orden (ascendente) especificado aquí',
	'fieldoptions' => 'Opciones de Campo',
	'optionvalues' => 'Valores de Opción',
	'optiondisplayorder' => 'Orden de Visualización',
	'optionisselected' => '¿Está seleccionado?',
	'cfieldinsertconfirm' => 'El campo personalizado  "%s"  se ha insertado correctamente',
	'cfdepartments' => 'Departamentos',
	'desc_cfdepartments' => 'Selecciona los departamentos asociados al campo personalizado. Puedes usar esta función para mostrar un campo personalizado diferente en función del departamento.',
	'cfgroupd' => 'Grupo de Campo Personalizado',
	'desc_cfgroupd' => 'Selecciona un grupo de campo personalizado para este campo personalizado.',

	// Manage Fields
	'managefields' => 'Administrar Campos',
	'desc_customfields' => '',
	'fieldlist' => 'Lista de Campos',
	'cfdelconfirm' => 'Campo personalizado correctamente eliminado',
	'cfdelconfirmmsg' => '¿Seguro que deseas borrar este campo personalizado? Borrar un campo personalizado implica el borrado permanente del campo y todos sus valores almacenados. Esta acción es irreversible',

	// Edit Custom Field
	'invalidcustomfield' => 'Campo personalizado inválido',
	'editcfield' => 'Editar Campo Personalizado',
	'updatefield' => 'Actualizar Campo',
	'cfieldupdateconfirm' => 'El campo personalizado "%s" se ha actualizado correctamente',

	// Field List
	'field_text' => 'Texto',
	'desc_field_text' => 'Selecciona este tipo de campo para crear una entrada de texto.',
	'field_textarea' => 'Área de texto',
	'desc_field_textarea' => 'Selecciona este tipo de campo para crear una entrada de texto de varias líneas.',
	'field_password' => 'Contraseña',
	'desc_field_password' => 'Selecciona este tipo de campo para crear un campo de entrada de contraseña (área de texto enmascarada).',
	'field_checkbox' => 'Casillas',
	'desc_field_checkbox' => 'Selecciona este campo para crear una lista de casillas de marcación con posibilidad de selección múltiples.',
	'field_radio' => 'Radio',
	'desc_field_radio' => 'Selecciona este tipo de campo para mostrar una lista de botones de radio con una única selección posible.',
	'field_select' => 'Selección',
	'desc_field_select' => 'Selecciona este tipo de campo para crear una lista desplegable (elección única).',
	'field_file' => 'Archivo',
	'desc_field_file' => 'Selecciona este tipo de campo para crear un campo de envío de archivos (un único envío).',
	'field_selectmultiple' => 'Selección Múltiple',
	'desc_field_selectmultiple' => 'Selecciona este tipo de campo para crear una lista de selección múltiple.',
	'field_custom' => 'Personalizado',
	'desc_field_custom' => 'Selecciona este tipo de campo para crear una entrada de campos personalizables en ' . SWIFT_PRODUCT . '. Sin embargo, tendrás que añadir el código HTML necesario tú mismo en las plantillas de envío de tickets.',
);
?>