<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array (
	// Imported from v3
	'user' => 'Usuario',
	'tasknodue' => 's/a',
	'dupdatedtickets' => 'Tickets actualizados desde el último acceso:',
	'ddocs' => 'Documentación del Producto',

	// Staff Dashboard
	'overview' => 'Vista previa (Sin resolver)',
	'dashboard' => 'Panel de control',
	'quickinsert' => 'Inserción rápida',
	'ticket' => 'Ticket',
	'contact' => 'Contacto',
	'event' => 'Evento',
	'task' => 'Tarea',
	'news' => 'Novedades',
	'file' => 'Archivo',
	'article' => 'Artículo',
	'day' => 'Día',
	'week' => 'Semana',
	'workweek' => 'Semana laboral',
	'month' => 'Mes',
	'dashtoday' => 'hoy',
	'overduetickets' => 'Tickets Vencidos',
	'ticketsduetoday' => 'Tickets que vencen hoy',
	'dashtoday2' => 'Hoy',
	'dashnews' => 'Novedades (%s)',
	'dashnewstitle' => 'últimas noticias',
	'undated' => 'Sin fecha',
	'dashduetasks' => 'Tareas vencidas / tareas sin fecha de vencimiento',
	'tasksduetoday' => 'Tareas que vencen hoy',
	'nwpostedby' => 'Publicado por ',
	'nwpostedon' => ' el ',
	'nwread' => 'Leer',
	'statistics' => 'Estadísticas',
	'dnewtickets' => 'Nuevos tickets desde la última identificación:',
	'dnewchats' => 'Nuevos chats desde la última identificación:',
	'twtoday' => 'Hoy',
	'tabrecentchats' => 'Nuevos Chats',
	'tabrecentmessages' => 'Nuevos mensajes/cuestionarios',
	'lcchatid' => 'ID del Chat',
	'lcfullname' => 'Nombre completo',
	'lcstaff' => 'Personal',
	'lcdepartment' => 'Departamento',
	'lcmessageid' => 'ID del Mensaje',
	'lcsubject' => 'Asunto',
	'dashmytickets' => 'Mis Tickets',
	'dashunassigned' => 'Sin Asignar',
	'dashcomments' => 'Comentarios',
	'taboverduetickets' => 'Tickets Vencidos',
	'dashticketid' => 'ID del Ticket',
	'dashsubject' => 'Asunto',
	'dashowner' => 'Propietario',
	'dashdepartment' => 'Departamento',
	'dashstatus' => 'Estado',
	'dashdepartmentprogress' => 'Departamento',
	'dashstatusprogress' => 'Estado',
	'dashtypeprogress' => 'Tipo',
	'dashownerprogress' => 'Propietario',
	'dashpriorityprogress' => 'Prioridad',
	'unresolveddash' => 'Sin resolver',
	'unassigneddash' => 'Sin asignar',

	// Admin Dashboard
	'licunlimited' => '- Ilimitados -',
	'licdomains' => 'Dominio(s)',
	'licstaff' => 'Personal con Licencia',
	'licexpires' => 'Expora',
	'licowner' => 'Propietario',
	'licuniqueid' => 'ID Única',
	'licversion' => 'Versión',
	'licorganization' => 'Organización',
	'logfailure' => 'FALLO',
	'plogfrom' => 'De:',
	'plogto' => 'Para:',
	'plogsize' => 'Tamaño:',
	'plognosubject' => 'Sin Asunto',
	'showingmsg' => ' (Mostrando %d de %d)',
	'titletemplaterevert' => 'Plantilla: Se necesita revertir actualización',
	'msgtemplaterevert' => '"%d" plantilla(s) necesitan una restauración debido a una actualización reciente:',
	'titlelanguagerevert' => 'Idioma: Se necesita revertir una actualización',
	'msglanguagerevert' => '"%d" frase(s) de idioma necesitan una actualización debido a una actualización reciente:',
	'licensedetails' => 'Detalles de la Licencia',
	'latestkayakonews' => 'Últimas Novedades de Kayako',
	'tabwelcome' => 'Bienvenido',
	'tabrecentactivity' => 'Actividad Reciente',
	'tabalerts' => 'Alartas',
	'tabloginfailures' => 'Fallos de identificación',
	'taberrorlog' => 'Registro de Errores',
	'tabparserlog' => 'Registro de Procesos',
	'dashipaddress' => 'Dirección IP: ',
	'dashforwardedipaddress' => 'Dirección IP Alternativa: ',
	'dashuseragent' => 'Agente de Usuario: ',
	'dashinterface' => 'Interfaz: ',
	'titleloginfailuredetectedone' => 'Detectado Fallo de Identificación',
	'msgloginfailuredetectedone' => SWIFT_PRODUCT . ' ha detectado un fallo de Identificación. Puedes ver el registro completo en Registros > Registro de identificación.',
	'titleloginfailuredetected' => 'Detectados %d fallos de identificación',
	'msgloginfailuredetected' => SWIFT_PRODUCT . ' ha detectado %d fallos de identificación. Puedes ver el registro completo en Registros > Registro de identificación.',
	'titleparserlogfailuredetected' => 'Detectados %d fallos de registro de Procesos',
	'msgparserlogfailuredetected' => SWIFT_PRODUCT . ' ha detectado %d fallos de registro de procesos. Puedes ver el registro completo en Registros > Registro de Procesos.',
	'titleerrorsdetected' => '%d Error(es) Registrados',
	'msgerrorsdetected' => SWIFT_PRODUCT . ' ha registrado %d Error(es). Para resolver estos errores es recomendable contactar con el soporte de Kayako con todos los detalles del error.',
	'dashusername' => 'Usuario:',
	'dashemail' => 'Email:',
	'dashlastlogin' => 'Última identificación:',
	'dashversion' => 'versión',
	'dashproduct' => 'producto',
	'dashdashboard' => 'panel',
	'dproduct' => 'Producto:',
	'dversion' => 'Versión: ',
	'dbuildtype' => 'Tipo de Versión: ',
	'dbuilddate' => 'Fecha de Versión: ',
	'kayako' => 'Kayako',
	'dhomepage' => 'Inicio',
	'dsupportdesk' => 'Soporte',
	'dmembersarea' => 'Área de Usuarios',
	'dforums' => 'Foros de la Comunidad',
	'dtemplategroups' => 'Grupos de Plantillas:',
	'dtemplates' => 'Plantillas:',
	'dlanguages' => 'Idiomas:',
	'dphrases' => 'Frases:',
	'dcustomfields' => 'Campos Personalizados:',
	'dtasks' => 'Tareas Programadas:',
	'dtables' => 'Tablas de base de datos:',
	'ddatabasesize' => 'Tamaño base de datos:',
	'dstaff' => 'Usuarios Personal:',
	'ddepartments' => 'Departamentos:',
	'drecentactivity' => 'Actividad Reciente',
	'drecentactivitynone' => 'No hay información disponible sobre actividad reciente',
	'accreated' => 'CREADO',
	'acupdated' => 'ACTUALIZADO',
	'acdeleted' => 'ELIMINADO',
	'acother' => 'OTRO',
);
?>