<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array (
	// ======= BEGIN v4 LOCALES =======
	'titlespecifyvalidemail' => 'Dirección de correo inválida',
	'msgspecifyvalidemail' => 'Por favor, introduce una dirección de correo válida. Toda la correspondencia con respecto a este fallo se enviarán a esta dirección de correo.',
	'send' => 'Enviar',
	'ddbversion' => 'Versión de la base de datos: %s',
	'ddbtype' => 'Tipo de base de datos: %s',
	'configurationvariables' => 'Variables de Configuración',
	'phpmodule' => 'Módulo: <b>%s</b>',
	'killsessions' => 'Terminar Sesiones',
	'titlekillsession' => 'Terminadas "%d" Sesiones',
	'msgkillsession' => 'Se han terminado correctamente la siguientes sesiones.',
	'wineditcache' => 'Editar Cache: %s',
	'titlebugreportdispatched' => 'Enviado Informe de Fallo',
	'msgbugreportdispatched' => SWIFT_PRODUCT . ' ha enviado tu informe de fallo a Kayako. Uno de los representantes de Kayako contactará contigo en breve.',
	'rebuildcache' => 'Reconstruir Caché',
	'licunlimited' => '- ilimitado - ',
	'tabrebuildcache' => 'Reconstruir Caché',
	'cachename' => 'Nombre de Caché',
	'result' => 'Resultado',
	'failure' => 'Fallo',
	'success' => 'Correcto',
	'clearedcachedirectory' => 'Limpiado el Directorio de Caché',
	'licorganization' => 'Organización: ' ,
	'licproductpackage' => 'Paquete: ',
	'licstaffcount' => 'Personal con Licencia: ',
	// ======= END v4 LOCALES =======

	// ======= BEGIN v3 IMPORT =======
	'php_ini_memory_limit' => 'límite de direccionamiento de RAM de php.ini: %s',
	'php_uname' => 'Información extendida del SO del Servidor: %s',
	'swift_language_base_charset' => 'SWIFT juego de caracteres del idioma base: %s',
	'swift_language_html_charset' => 'SWIFT juego de caracteres de html: %s',
	'swift_language_text_charset' => 'SWIFT Juego de caracteres del texto: %s',
	'swift_language_html_encoding' => 'SWIFT Codificación lenguaje html: %s',
	'swift_language_text_encoding' => 'SWIFT Codificación lenguaje de texto: %s',
	'php_installed_modules' => 'Módulos PHP instalados: %s',
	'disk_free_space' => 'Espacio libre actualemente en el servidor: %s de %s bytes',
	'php_ini_max_execution_time' => 'Tiempo máximo de ejecución PHP INI: %s',
	'php_ini_display_errors' => 'Visualización Errores PHP: %s',
	'php_ini_quiet_eval' => 'Modo de Evaluación Silenciosa de PHP: %s',
	'php_ini_error_reporting' => 'Nivel de Notificación de Errores PHP: %s',
	'php_ini_output_buffering' => 'PHP Output Buffering: %s',
	'zend_version' => 'Versión de Zend: %s',
	'php_ini_register_globals' => 'Register Globals: %s',
	'php_ini_magic_quotes_gpc' => 'Magic Quotes GPC: %s',
	'php_ini_magic_quotes_runtime' => 'Magic Quotes Runtime: %s',
	'php_ini_post_max_size' => 'Tamaño Máximo de POST: %s',
	'php_ini_upload_max_size' => 'Maximum upload size: %s',
	'php_ini_allow_calltime_pass_reference' => 'PHP permite call-time reference passage: %s',
	'php_ini_allow_url_fopen' => 'PHP permite URL fopen(): %s',
	'php_ini_always_populate_raw_post_data' => 'Forzar el llenado de POST con raw data: %s',
	'php_ini_default_charset' => 'Juego de caracteres por defecto para el servidor: %s',
	'php_ini_default_mimetype' => 'Tipo MIME por defecto para el servidor: %s',
	'php_ini_display_startup_errors' => 'PHP muestra errores de inicio: %s',
	'php_ini_expose_php' => 'PHP se muestra: %s',
	'php_ini_ignore_repeated_errors' => 'PHP ignora errores repetidos: %s',
	'php_ini_max_input_time' => 'Tiempo de salida INI Max: %s',
	'php_ini_output_handler' => 'Gestor global de salida: %s',
	'php_ini_report_zend_debug' => 'Reportar zend debugging calls: %s',
	'php_ini_safe_mode' => 'PHP está en modo segurp: %s',
	'php_ini_bug_compat_42' => 'Modo 42 de compatibilidad INI: %s',
	'php_ini_bug_compat_warn' => 'Aviso de modos INI de compatibilidad: %s',
	'php_ini_track_errors' => 'Seguimiento de errores PHP: %s',
	'php_ini_upload_max_filesize' => 'Tamaño máximo de subida de archivos: %s',
	'php_ini_zend_1_compatibility_mode' => 'Modo de compatibilidad Zend 1: %s',
	'php_rusage' => 'RUsage: %s',
	'licfullname' => 'Nombre registrado: ',
	// ======= END v3 IMPORT =======
	'diagnostics' => 'Diagnósticos',
	'phpinfo' => 'PHP Info',
	'desc_phpinfo' => 'A continuación se muestran los detalles de configuración PHP de tu servidor. Para más información con la función  phpinfo() visita <a href="http://www.php.net/phpinfo" target="_blank">http://www.php.net/phpinfo</a>.',
	'mysqlinfo' => 'MySQL Info',
	'desc_mysqlinfo' => 'A continuación se muestran los detalles de configuración MySQL de tu servidor. Los valores de estas variables están especificados en el archivo my.cnf que suele ubicarse en el directorio <i>etc</i>.',
	'variable' => 'Variable',
	'value' => 'Valor',
	'cachetitle' => 'Título Caché',
	'cacheinfo' => 'Info Cache',
	'desc_cacheinfo' => 'La información y datos generados con frecuencia quedan en caché, reduciendo la necesidad de ejecutar peticiones repetidas a la base de datos.',

	// Report Bug
	'reportbug' => 'Informar de Fallo',
	'desc_reportbug' => 'Puedes informar un fallo al equipo de Kayako facilitando una breve descripción del problema a continuación. Es recomendable que conservas la información de debug ya que nos ayudará a resolver el problema más rápidamente. Por favor, asegúrate de que la dirección de correo indicada es correcta.',
	'bugdetails' => 'Informe de Fallos',
	'submitbug' => 'Enviar Fallo',
	'bugsubject' => 'Asunto',
	'desc_bugsubject' => 'Introduce un título para este aviso de fallo.',
	'bugfromname' => 'Nombre completo',
	'desc_bugfromname' => 'Introduce tu nombre o el de la persona con la que debemos contactar en tu organización.',
	'bugfromemail' => 'Dirección de correo electrónico',
	'desc_bugfromemail' => 'Esta es el correo que se usará en el campo <b>De</b> para el informe enviado a Kayako. Por favor, asegúrate de que sea una dirección de correo válida.',
	'debuginfo' => '### Debug Info ###',
	'dphpversion' => 'PHP Version: %s',
	'dphpuploadsize' => 'Max Upload Size: %s',
	'dphpsafemode' => 'Safe Mode: %s',
	'dswifturl' => 'Installation URL: %s',
	'dswiftproduct' => 'Product: %s',
	'dswiftversion' => 'Version: %s',
	'dswiftbuilddate' => 'Build Date: %s',
	'dswiftbuildtype' => 'Build Type: %s',
	'dmysqlversion' => 'MySQL Version: %s',
	'duseragent' => 'User Agent: %s',
	'dserversoftware' => 'Server Software: %s',
	'dos' => 'Operating System: %s',
	'specifyvalidemail' => 'ERROR: Por favor, indica una dirección de correo válida',
	'bugreportdispatched' => 'Informe de fallo enviado a bugs@kayako.com',

	// License Information
	'licenseinfo' => 'Información de Licencia',
	'desc_licenseinfo' => '',
	'liccreated' => 'Creada el: ',
	'licnever' => '-- Nunca --',
	'licexpiry' => 'Fecha de Caducidad: ',
	'licuniqueid' => 'Unique ID: ',
	'licproduct' => 'Producto: ',
	'licdomains' => 'Dominios Registrados',
	'licdomform' => 'Dominio #%s',

	// Active Sessions
	'activesessions' => 'Sesiones Activas',
	'desc_activesessions' => '',
	'sess' . SWIFT_Interface::INTERFACE_API => 'API',
	'sess' . SWIFT_Interface::INTERFACE_STAFF => 'Personal',
	'sess' . SWIFT_Interface::INTERFACE_ADMIN => 'Admin',
	'sess' . SWIFT_Interface::INTERFACE_CLIENT => 'Cliente',
	'sess' . SWIFT_Interface::INTERFACE_WINAPP => 'Winapp',
	'sess' . SWIFT_Interface::INTERFACE_CONSOLE => 'Consola',
	'sess' . SWIFT_Interface::INTERFACE_VISITOR => 'Visitante',
	'sess' . SWIFT_Interface::INTERFACE_CHAT => 'Chat',
	'sess' . SWIFT_Interface::INTERFACE_ARCHIVE => 'Archivo',
	'sess' . SWIFT_Interface::INTERFACE_PDA => 'PDA',
	'sess' . SWIFT_Interface::INTERFACE_RSS => 'RSS',
	'sess' . SWIFT_Interface::INTERFACE_SYNCWORKS => 'SyncWorks',
	'sessionlist' => 'Lista de Sesiones',
	'ipaddress' => 'Dirección IP',
	'lastactivity' => 'Última Actividad',
	'sessiontype' => 'Tipo de Sesión',
	'useragent' => 'Agent de Usuario',
	'killsession' => 'Cerrar Session',
	'sessiondelconfirm' => 'Sesión cerrada correctamente',
	'sess' . SWIFT_Interface::INTERFACE_INSTAALERT => 'InstaAlert',
);

?>