<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array (
	// ======= BEGIN v4 LOCALES =======
	'insertbreakline' => 'Insertar Salto de Línea',
	'editbreakline' => 'Editar Salto de Línea',
	'emailqueues' => 'Colas de Correo',
	'winviewparserlog' => 'Ver Registro de Proceso',
	'close' => 'Cerrar',
	'titleparserlogdel' => 'Eliminados "%d" Registro(s) de Proceso',
	'msgparserlogdel' => 'Se han eliminado correctamente las siguientes entradas del registro de procesos de la base de datos:',
	'breaklines' => 'Salto de líneas',
	'desc_breaklines' => '',
	'isregexp' => '¿Expresión Regular?',
	'sortorder' => 'Orden de Visualización',
	'wineditbreakline' => 'Editar Salto de línea',
	'breaklinetitle' => 'Texto Salto de línea',
	'desc_breaklinetitle' => 'Introduce el texto de salto de línea, todos los correos entrantes se cortarán hasta la línea que contenga el texto de salto.',
	'desc_sortorder' => 'Introduce el orden de saltos de línea.',
	'isregexp' => 'Es Regex?',
	'desc_isregexp' => 'Si se activa, el texto de salto se tratará como una expresión regular.',
	'titleinsertbreakline' => 'Salto de línea insertado',
	'msginsertbreakline' => 'El procesador de saltos de línea se ha insertado correctamente en la base de datos.',
	'titleupdatebreakline' => 'Salto de línea actualizado',
	'msgupdatebreakline' => 'Se ha actualizado correctamente el procesador de salto de línea.',
	'titledelbreakline' => '"%d" saltos de línea eliminados',
	'msgdelbreakline' => 'Se han eliminado correctamente los siguientes saltos de línea de la base de datos:',
	'invalidbreakline' => 'Salto de línea inválido. Por favor, asegúrate de que el salto de línea existe en la base de datos y que la base de datos no está corrupta.',
	'tabsettings' => 'Ajustes',
	'forcequeue' => 'Forzar a la cola los correos entrantes',
	'desc_forcequeue' => 'Si se activa, el sistema forzará a todos los correos entrantes en la bandeja de entrada a usar la misma cola desde la que el correo se descarga. Si  pretentes usar esat cola como un volcado de los correos reenviados es recomendable que desactives esta opción.',
	'leavecopyonserver' => '¿Dejar copia en el servidor?',
	'desc_leavecopyonserver' => 'Si se activa, el sistema dejará una copia del mensaje en el servidor de correo. Por defecto, el sistema vacía la bandeja de entrada una vez que el proceso de obtención de correo se ha compltado.<br /><b><font color="red">NOTA:</font></b> Esta opción únicamente funciona con bandejas de correo IMAP.',
	'nonssl' => 'Sin SSL',
	'tls' => 'TLS',
	'ssl' => 'SSL',
	'sslv2' => 'SSL v2',
	'sslv3' => 'SSL v3',
	'usequeuesmtp' => 'Usar cola del servidor SMTP',
	'desc_usequeuesmtp' => 'Si se activa, el servidor especificado se usará para enviar todos los correos relacionados con esta cola de correo. Esto evita que el correo sea etiquetado como spam.',
	'smtptype' => 'Tipo de SMTP',
	'desc_smtptype' => 'Selecciona el tipo de servidor SMTP.',
	'next' => 'Siguiente',
	'titleinvalidqueueprefix' => 'Prefijo de cola inválido',
	'msginvalidqueueprefix' => 'Por favor, especifica un prefijo de cola de correo válido. Únicamente se permiten caracteres alfanuméricos.',
	'titlefailedtocreatequeue' => 'Fallo al crear la cola',
	'msgfailedtocreatequeue' => 'No se pudo crear la cola. Por favor, revisa la configuración de tu base de datos y los ajustes de conexión.',
	'back' => 'Atrás',
	'wineditemailqueue' => 'Editar Cola de Correo',
	'tabticketsettings' => 'Opciones de Ticket',
	'tabpop3imap' => 'POP3/IMAP',
	'queueisenabled' => '¿Activo?',
	'desc_queueisenabled' => '¿se se activa la cola procesará todos los mensajes entrantes que se envíen a la dirección de correo especificada. Desactivar la cola resultará en un rechazo silencioso de todos los mensajes entrantes mediante pipa o pop3.',
	'titlequeueinsert' => 'Cola de Correo Insertada',
	'msgqueueinsert' => 'Se ha insertado correctamente la cola de correo "%s" en la base de datos.',
	'titlequeueupdate' => 'Cola de correo Actualizada',
	'msgqueueupdate' => 'Se ha actualizado correctamente la cola de correo "%s".',
	'titledelqueues' => 'Eliminadas "%d"colas de correo',
	'msgdelqueues' => 'Se han eliminado correctamente las siguientes colas de correo de la base de datos:',
	'titlestaffemail' => 'Dirección de correo inválida',
	'msgstaffemail' => SWIFT_PRODUCT . ' no puede insertar/actualizar la dirección de cola de correo puesto que la dirección de correo especificada están está asginada a "%s" usuario de personal. Esta comprobación se realiza para evitar que sucedan bucles de correo.',
	'verifyconnection' => 'Verificar Conexión',
	'vcvariablesanity' => 'Comprobando la información de cola del servidor.',
	'vcimapnotcompiled' => 'Tu PHP no está compilado con soporte IMAP support. Los usuarios *nix deberían recompilar su PHP con la opción \'--with-imap\'; los usuarios de Windows pueden, simplemente, descomentar la extensión=\'php_imap.dll\' en su php.ini',
	'vcimapcompiled' => 'PHP está compilado con soporte IMAP',
	'vcattemptconnection' => 'Intentando conectar con el servidor POP3/IMAP',
	'vcconnectionsuccess' => 'Conexión Correcta',
	'vctotalmessages' => 'Total de Mensajes en la Bandeja de Entrada: %d',
	'vcconnectionfailed' => 'Fallo en la conexión a la Bandeka de Entrada:<BR />%s',
	'erremailqueuesame' => 'El correo ha sido rechazado puesto  que el correo de origen está incluido en la cola de correo',
	// ======= END v4 LOCALES =======

	// ======= BEGIN v3 CVS UPDATE IMPORT =======
	'queue_id_label' => 'ID',
	'managemailqueue' => 'Administrar Colas de Correo',
	'invalidqueueaddress' => 'Debes introducir una dirección de correo válida para la cola.',
	'fetchpop3tls' => 'POP3 TLS',
	'fetchimaptls' => 'IMAP TLS',
	'errloopcontrol' => 'Mensaje bloqueado debido a una regla de control de bucle.',
	'errorlockfilefound' => '[ERROR]: Se encontró un bloqueo de archivo (./files/parser.lockfile). Se ha encontrado un bloqueo de archivo que evita continuar con la ejecución. Si es debido a una copia de ejecución de cron entonces por favor borra el archivo para continuar. Para borrar el archivo de forma manual <a href="%s">pincha aquí</a>',
	'lockfileexpired' => '[AVISO]: Bloqueo finalizado del archivo (./files/parser.lockfile) de una copia anterior de cron localizada; borrando automáticamente...',
	'errtoobig' => 'Tamaño máximo de archivo permitido superado (%s); tamaño del mensaje: %s',
	'autorespondernotsent' => ' (No se envió la autorespuesta debido a los ajustes actuales)',
	// ======= END v3 CVS UPDATE IMPORT =======

	'mailparser' => 'Procesador de Correo',
	'desc_mailparser' => '',
	'queuelist' => 'Lista de Cola de Correo',

	'insertemailqueue' => 'Insertar Cola de Correo',
	'queuedetails' => 'Detalles de la Cola',
	'insertqueue' => 'Insertar Cola',
	'queuenextstep' => 'Siguiente &raquo;',
	'emailgeneralfields' => 'Campos de correo',
	'emailimapfields' => 'Información de Identificación (únicamente necesaria si se selecciona POP3/IMAP)',
	'emailaddress' => 'Dirección de cola de correo',
	'desc_emailaddress' => 'Introduce una dirección de correo válida para la cola. Por ejemplo, soporte@dominio.com',
	'emailtype' => 'Tipo de Cola',
	'desc_emailtype' => '',
	'emailfetchtype' => 'Tipo de Obtención',
	'desc_emailfetchtype' => 'Especifica cómo obtendrá el correo el procesador. Todas las opcioens, salvo <i>Pipa</i> necesitan nombre de servidor, de usuario y contraseña.',
	'fetchpipe' => 'Pipa',
	'fetchpop3' => 'POP3',
	'fetchpop3ssl' => 'POP3 SSL',
	'fetchimap' => 'IMAP',
	'fetchimapssl' => 'IMAP SSL',
	'emailhost' => 'Servidor',
	'desc_emailhost' => 'Introduce el nombre del servidor de correo. Esto puede ser una dirección IP o un nombre de dominio como <i>mail.dominio.com</i>.',
	'emailport' => 'Puerto',
	'desc_emailport' => 'Especifica el puerto del servidor de correo. Es recomendable que este valor se deje sin cambiar a menos que el servidor funcione en un puerto diferente a la configuración por defecto.',
	'emailusername' => 'Nombre de usuario',
	'desc_emailusername' => 'Introduce el nombre de usuario para el servidor.',
	'emailpassword' => 'Contraseña',
	'desc_emailpassword' => 'Introduce la contraseña del servidor.',

	'queueoverrides' => 'Reemplazo de Cola (Opcional)',
	'queuefromname' => 'De (nombre)',
	'desc_queuefromname' => 'Si se especifica, todos los correos salientes bajo esta cola tendrán el nombre del campo <i>De</i> remplazado por nombre aquí indicado.',
	'queuefromemail' => 'Desde (correo)',
	'desc_queuefromemail' => 'Si se especifica, todos los correos salientes bajo estas cola tendrán el campo <i>Desde</i> reemplazado por esta dirección.',

	'queuesettings' => 'Ajustes de Cola',
	'templategroup' => 'Grupo de Plantilla de Cola',
	'desc_templategroup' => 'Selecciona el grupo de plantilla de cola. Los ajustes y plantillas de este grupo de plantillas se usarán para los correos nuevos de la cola.',
	'queuesignature' => 'Firma de cola (Opcional)',
	'desc_queuesignature' => 'Introduce la firma de la cola. Esta firma se añadirá a todos los correos salientes de esta cola.',
	'registrationrequired' => '¿Necesario registrarse?',
	'desc_registrationrequired' => 'Si se activa, únicamente los usuarios <b>registrados</b>  podrán enviar nuevos tickets a esta dirección y cola de correo. Los usuarios no registrados podrán seguir enviando tickets a través del sistema de soporte.',
	'issueautoresponder' => '¿Activar Autorrespuesta para Nuevos Tickets?',
	'desc_issueautoresponder' => 'Si se activa, el sistema enviará una autorespuesta para confirmar la recepción de un nuevo ticket.',
	'replyautoresponder' => '¿Activar Autorespuesta para Nuevas Respuestas??',
	'desc_replyautoresponder' => 'Si se activa, el sistema enviará un mensaje de autorespuesta confirmando la recepción de una nueva respuesta para un ticket ya creado.',

	'ticketfields' => 'Campos de Ticket',
	'queuedepartment' => 'Departamento',
	'desc_queuedepartment' => 'Especifica el departamento bajo el que se crearán los nuevos tickets.',
	'queuetickettype' => 'Tipo de Ticket',
	'desc_queuetickettype' => 'Selecciona el tipo de ticket para esta cola. Cualquier ticket creado bajo esta cola quedará definido del tipo indicado aquí.',
	'queueticketstatus' => 'Estado del Ticket',
	'desc_queueticketstatus' => 'Selecciona el estado para esta cola. Todos los tickets de nueva creación tendrán el estado aquí especificado',
	'queuepriority' => 'Prioridad de Ticket',
	'desc_queuepriority' => 'Selecciona la prioridad de ticket para esta cola. Esto no está relacionado con la "Prioridad" de un correo entrante. Todos los tickets creados en esta cola tendrán asignada esta prioridad.',
	'failedtocreatequeue' => 'ERROR: No se pudo crear la cola de correo',
	'redirect_queueinsert' => 'Cola de correo insertada correctamente.',
	'queueinsertconfirm' => 'La cola de correo "%s" se ha insertado correctamente',
	'depdeleteconfirm' => 'La cola de correo "%s" se ha borrado correctamente',
	'invalidemailqueue' => 'La cola de correo especificada es inválida',
	'editemailqueue' => 'Editar Cola de Correo',
	'emailqueues' => 'Colas de Correo',
	'queueupdconfirm' => 'Cola de correo "%s" actualizada correctamente',
	'invalidparserlog' => 'Entrada de registro de proceso inválida. Asegúrate de que el registro de procesos de correo existe en la base de datos y no ha sido eliminado.',
	'desc_parserlog' => 'El procesador registra todos los correos entrantes con información de utilidad que puede ayudar a resolver algunos problemas. Para desactivar el registro de correos o cambiar otros ajustes, ve a <i>Ajustes > Procesador de Correo</i>.',
	'desc_mailparser' => 'El procesador de correo es una componente crucial de '. SWIFT_PRODUCT .'. Incluye algunas potentes características como el procesador de reglas, reglas para todas las cuentas, saltos de línea y prohibiciones para simplificar el flujo de trabajo. El procesador de correo usa colas de correo para asociar diversa información con un departamento o para averiguar a qué departamento debería dirigirse un correo entrante. Para más información, por favor, consulta la sección Procesador de correo (Mail Parser) en el manual de usuario.',
	'queueprefix' => 'Prefijo de Asunto de Cola (Opcional)',
	'desc_queueprefix' => 'Si se indica, todos los asuntos de los correos bajo esta cola tendrán un prefijo. Por ejemplo, si indicas que el prefijo de cola de correo sea <i>SOPORTE</i> el asunto de los correos salientes será: <i>[SOPORTE #ABC-12345]: Asunto Real</i>',
	'invalidqueueprefix' => 'Prefijo de cola inválido. Únicamente pueden usarse valores alfanuméricos (A-Z, 0-9) y espacios.',

	'titleenablequeues' => 'Activadas "%d" Colas de Correo',
	'msgenablequeues' => SWIFT_PRODUCT . ' ha activado correctamente las siguientes colas de correo:',
	'titledisablequeues' => 'Desactivadas "%d" Colas de Correo',
	'msgdisablequeues' => SWIFT_PRODUCT . ' ha desactivado correctamente las siguientes colas de correo:',

	// View Parser Log
	'viewparserlog' => 'Ver Registro de Procesos',
	'parserlogentry' => 'Registro de Procesos #%s',
	'generalinformation' => 'Información General',
	'mimedata' => 'Datos MIME',
	'ppticketid' => 'Ticket ID: ',
	'ppticketmaskid' => 'Ticket Mask ID: ',
	'ppdate' => 'Fecha: ',
	'pptimeline' => 'Progreso: ',
	'ppemailqueue' => 'Cola de Correo: ',
	'ppstatus' => 'Estado de Proceso: ',
	'ppsubject' => 'Asunto: ',
	'ppfromemail' => 'Desde: ',
	'pptoemail' => 'Destinatario: ',
	'ppsize' => 'Tamaño: ',
	'pptimetaken' => 'Tiempo empleado: ',
	'ppdesc' => 'Descripción: ',
	'ppresult' => 'Resultado',
	'pparserlogid' => 'ID del registro de proceso: ',

	// Parser Log
	'parserlog' => 'Registro de Proceso',
	'parserlogs' => 'Registros de Proceso',
	'emailsubject' => 'Asunto Correo',
	'emailsubjectresult' => 'Asunto y Resultado de Correo',
	'emailstatus' => 'Estado',
	'emailsubresultformat' => '%s<BR /><B>Resultados:</B> %s',
	'emailparsetime' => 'Fecha de Proceso',
	'emailfrom' => '"De:" Email',
	'emailto' => '"Para:" Email',
	'emaildescription' => 'Descripción',
	'emailticketid' => 'Ticket/Bug ID',
	'emailticketmaskid' => 'Ticket Mask ID',
	'emailcontents' => 'Contenidos de Correo',

	'nosubject' => '(Sin Asunto)',


	// Breaklines
	'breaklines' => 'Saltos de Línea',
	'desc_breaklines' => 'La función de Saltos de Línea en '. SWIFT_PRODUCT .' evita que se añada contenido ya citado en el correo. '. SWIFT_PRODUCT .' cortará todo el texto que sigue al salto de línea. Esta función ayuda a mantener el contenido del correo entrante "limpio". Si el contenido de respuesta está alguna vez vacío, todo el mensaje se almacenará en la base de datos. Ejemplo:<BR /><BR /><b>Correo Original:</b><BR />Contenido de Respuesta<BR />-----Mensaje Original-----<BR />Mensaje Citado<BR /><BR /><b>Resultado:</b><BR />Contenido Respuesta<BR /><BR />',
	'breaklinelist' => 'Lista de Saltos',
	'breakline' => 'Salto de Línea',
	'insertbreakline' => 'Insertar Salto',
	'desc_breakline' => 'Introduce los contenidos de salto que deseas insertar.<BR /><BR />Nota: Para usar expresiones regulares precede tu salto con "regex:"<BR />Ejemplo: <i>"regex:@[-=]{4,}[^-=]+[-=]{4,}@"</i>',
	'breaklinedelconfirm' => 'Salto de línea eliminado correctamente',
	'breaklineinsertconfirm' => 'Salto de línea correctamente insertado',

	// Parser Errors
	'errnorecipients' => 'No se encontraron destinatarios',
	'errnofromemail' => 'No se especificó una dirección de correo',
	'errnoqueues' => 'No se encontraron colas para los destinatarios de correo',
	'errfloodprotection' => 'Se activó la protección de Saturación',
	'scccreatedticket' => 'Creado ticket #%s',
	'scccreatedreply' => 'Creada respuesta #%s al ticket #%s',
	'sctcreatedreply' => 'Creada respuesta desde terceros #%s al ticket #%s',
	'scccreatedstaffreply' => 'Creada respuesta del personal #%s al ticket #%s',
	'clearedduelimit' => '-- datos MIME limpiados debido al límite de tamaño definido en Ajustes > Procesador --',
	'errusernotreg' => 'El usuario %s no está registrado. Los ajustes de cola requieren que el usuario esté registrado.',
	'erremailbanned' => 'La dirección de correo está bloqueda',
	'actionrepprefix' => 'Re: ',

	// Misc
	'reprocessemail' => 'Reprocesar Correo',

	// Loop Cutter
	'pr_loopcutter_prevents_autoresponder_desc' => ' (Autorespuesta no enviada debido a control de bucle)',
	'pr_mangelooprules' => 'Reglas de Bucle',
	'pr_loopcontrolrules' => 'Reglas de Control de Bucle',
	'pr_manageloopblockages' => 'Bloqueos de Bucle',
	'pr_loopblockages' => 'Bloqueos de Bucle',
	'pr_insert_new_loopcutter_rule_title' => 'Insertar Regla de Control de Bucle',
	'pr_edit_new_loopcutter_rule_title' => 'Editar Regla de Control de Bucle',
	'pr_threshhold_grid_timeframe_title' => 'Marco de tiempo',
	'pr_threshhold_grid_maxhits_title' => 'Max Hits',
	'pr_threshhold_grid_restoreafter_title' => 'Restaurar Tras',
	'pr_threshhold_grid_address_title' => 'Dirección',
	'pr_new_loop_control_header_text' => 'Nuevo Control de Bucle',
	'pr_newloopcontrolwatchlength_title' => 'Marco de vigilancia',
	'pr_newloopcontrolwatchlength_desc' => 'Esta es la longitud del marco de tiempo que el bloquador de bucles tiene en cuenta, medido en segundos.',
	'pr_newloopcontrolmaxcontacts_title' => 'Contactos máximos',
	'pr_newloopcontrolmaxcontacts_desc' => 'Este es el número de correos enviados que activará un bloqueo de bucles.',
	'pr_newloopcontrolrestoreafter_title' => 'Restaurar Tras',
	'pr_newloopcontrolrestoreafter_desc' => 'Esta es la cantidad de tiempo tras la que un bloqueo de bucle se eliminará de forma automática, medida en segundos.',
	'pr_new_loop_control_rule_added_desc' => 'Añadida nueva regla de control de bucles.',
	'pr_desc_loopblockages_filler' => 'A continuación está una lista de los bloqueos de bucle activos.  Las direcciones listadas aquí activaron una o más reglas de control de bucles. (<i>Procesador de Correo >> Administrar Reglas de Bucle</i>).  Dependiendo de los ajustes activos (<i>Ajustes >> Procesador de Correo >> Ajustes de control de bucles</i>), los correos entrantes desde estas direcciones puede ser completamente ignorados por ' . SWIFT_PRODUCT . ' y un mensaje de autorespuesta podría no ser enviado. Estos ajustes entrarán en efecto para cada bloqueo hasta que expire.',
	'pr_desc_looprules_filler' => 'A continuación hay una lista de control de reglas de control de bucles. Estas reglas evitan bucles de autorespuesta u otras situaciones de saturación y todos los correos entrantes están sujetos a ellas. Si una regla se activa, se aplicarán los ajustes (<i>Ajustes >> Procesador de Correo >> Ajustes de Control de Bucles</i>).  Esto permite a ' . SWIFT_PRODUCT . ' ignorar completamente el mensaje y/o no enviar mensaje de autorespuesta. Los bloqueos creados por estas reglas se eliminan automáticamente tras el tiempo especificado.',
	'pr_loop_rule_deleted' => 'Regla eliminada.',
	'pr_loop_block_deleted' => 'Bloqueo eliminado.',
	'invalidlooprule' => 'Recla de corte de bucle iválida. Por favor, asegúrate de que el registro existe en la base de datos.',
	'wineditloopcutterrule' => 'Editar Regla de Corte de Bucle',
	'pr_threshhold_grid_title' => 'Título de la Regla Marco',
	'thresholdruletitle' => 'Título de la Regla de Bucle',
	'desc_thresholdruletitle' => 'Introduce el título de tu Regla de Bucle',
	'titledelloopblock' => 'Eliminados "%d" Bloqueo(s) de Bucle',
	'msgdelloopblock' => 'Se han eliminado correctamente los siguientes Bloqueos de Bucle de la base de datos:',
	'titledellooprule' => 'Eliminadas "%d" Reglas de Bucle',
	'msgdellooprule' => 'Se han eliminado correctamente las siguientes Reglas de Bucle de la baee de datos:',
	'titleinsertlooprule' => 'Insertada Regla de Bucle',
	'msginsertlooprule' => 'Se ha insertado correctamente la Regla de Bucle en la base de datos:',
	'titleupdatelooprule' => 'Regla de Bucle Actualizada',
	'msgupdatelooprule' => 'Regla de Bucle Actualizada correctamente:',
	'titlelooprulemasterdel' => 'No se puede eliminar la regla de bucles maestra',
	'msglooprulemasterdel' => SWIFT_PRODUCT . ' no puede eliminar las siguientes reglas de bucle maestras):',
);
?>